### ISSUE TITLE
No such file or directory model_8855.mlmodel

### ISSUE THREAD

**Issue by PonteIneptique** [mittagessen/kraken#101]
Using latest ( https://github.com/mittagessen/kraken/commit/d139015732c1d953a5375a6c00bd235c0c965e52 ) master  and installing using the .travis.yml installation procedure (albeit using regular torch nightly for GPU capacities), I run into 

```python-traceback
[110.3317] Moving best model model_8855.mlmodel (0.9698731501057083) to model_best.mlmodel 
Traceback (most recent call last):
  File "/home/thibault/miniconda3/envs/ocr/bin/ketos", line 10, in <module>
    sys.exit(cli())
  File "/home/thibault/miniconda3/envs/ocr/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/thibault/miniconda3/envs/ocr/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/thibault/miniconda3/envs/ocr/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/thibault/miniconda3/envs/ocr/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/thibault/miniconda3/envs/ocr/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/thibault/miniconda3/envs/ocr/lib/python3.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/thibault/miniconda3/envs/ocr/lib/python3.7/site-packages/kraken/ketos.py", line 382, in train
    shutil.copy('{}_{}.mlmodel'.format(output, st_it.best_iteration), '{}_best.mlmodel'.format(output))
  File "/home/thibault/miniconda3/envs/ocr/lib/python3.7/shutil.py", line 241, in copy
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/home/thibault/miniconda3/envs/ocr/lib/python3.7/shutil.py", line 120, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: 'model_8855.mlmodel'
```

Run with `ketos -v train --savefreq 1000 --device cuda:0 SynLat/*.png`

**Comment by PonteIneptique** [comment]
Note that the same command without `--savefreq 1000` works :)

**Comment by mittagessen** [comment]
Yes, that is working as intended. You're saving your model every 1000 epochs and run the evaluation every epoch. After ~8000 lines the early stopping aborts the training but no model as been saved, yet. Set `--report` to the same value as `--savefreq` and both ideally to 1 and it should work.  Mind that the frequency switches on `ketos train` are epoch-wise.

**Comment by PonteIneptique** [comment]
Thanks :)
