### ISSUE TITLE
Received 0 items of ancdata

### ISSUE THREAD

**Issue by Jean-Baptiste-Camps** [mittagessen/kraken#110]
I have encountered this bug, while training on a few datasets usually extracted with OCRopy:

```
stage 0/∞  [#####-------------------------------]  505/3272  00:27:39
Traceback (most recent call last):
  File "/home/jbc/Data/F/LAKME/01_ocerisation/MSS/env/bin/ketos", line 11, in <module>
    sys.exit(cli())
  File "/home/jbc/Data/F/LAKME/01_ocerisation/MSS/env/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/jbc/Data/F/LAKME/01_ocerisation/MSS/env/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/jbc/Data/F/LAKME/01_ocerisation/MSS/env/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/jbc/Data/F/LAKME/01_ocerisation/MSS/env/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/jbc/Data/F/LAKME/01_ocerisation/MSS/env/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/jbc/Data/F/LAKME/01_ocerisation/MSS/env/lib/python3.6/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/jbc/Data/F/LAKME/01_ocerisation/MSS/env/lib/python3.6/site-packages/kraken/ketos.py", line 346, in train
    for _, (input, target) in zip(range(eval_it), st_it):
  File "/home/jbc/Data/F/LAKME/01_ocerisation/MSS/env/lib/python3.6/site-packages/kraken/lib/train.py", line 160, in __next__
    return next(self.it)
  File "/home/jbc/Data/F/LAKME/01_ocerisation/MSS/env/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 631, in __next__
    idx, batch = self._get_batch()
  File "/home/jbc/Data/F/LAKME/01_ocerisation/MSS/env/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 610, in _get_batch
    return self.data_queue.get()
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 113, in get
    return _ForkingPickler.loads(res)
  File "/home/jbc/Data/F/LAKME/01_ocerisation/MSS/env/lib/python3.6/site-packages/torch/multiprocessing/reductions.py", line 256, in rebuild_storage_fd
    fd = df.detach()
  File "/usr/lib/python3.6/multiprocessing/resource_sharer.py", line 58, in detach
    return reduction.recv_handle(conn)
  File "/usr/lib/python3.6/multiprocessing/reduction.py", line 182, in recv_handle
    return recvfds(s, 1)[0]
  File "/usr/lib/python3.6/multiprocessing/reduction.py", line 161, in recvfds
    len(ancdata))
RuntimeError: received 0 items of ancdata
```

I guess it has to do with the data, but there seems not to be  `.png` files without `.gt.txt` (or the contrary).

I'm using the pip version with Python3.6 in a virtualenv on Ubuntu 16.04.

**Comment by mittagessen** [comment]
This error is caused by low system file descriptor limits. If you have to rights I would suggest setting a higher number by running `limit -n unlimited`. Alternatively, adding the `--threads 0` option will cause the training data to be loaded in the main thread which should also prevent this issue from popping up.

There is an alternative multiprocessing strategy supported in the pytorch data loaders but that one has a bunch of other drawbacks. I'll run some tests and if I can't trigger any undesired behavior I'll switch to that one by default.

**Comment by Jean-Baptiste-Camps** [comment]
Thanks ! `--threads 0` indeed worked around the problem and I was able to train !
