### ISSUE TITLE
Error: Invalid value: No model for default found

### ISSUE THREAD

**Issue by msh2050** [mittagessen/kraken#111]
Dears after hours of trying to get kraken work on windows I reached to this level
then I give up and start my virtual machine to test and I get the same error
Please this is as instructed by the quick start .... what I have missed..?!

regards

`(kraken) :~/Downloads$ kraken get arabic-amiri
Retrieving model ...........................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................✓
(kraken) :~/Downloads$ dir
Augie_Part11.jpg

(kraken) :~/Downloads$ kraken -i Augie_Part11.jpg  image.txt binarize segment ocr -m arabic-amiri
Usage: kraken ocr [OPTIONS]

Error: Invalid value: No model for default found

`

**Comment by msh2050** [comment]
I down loaded the ready kraken virtual box (Xubuntu) with same error....
regards

**Comment by mittagessen** [comment]
I'm in the process of moving the model repository to zenodo and haven't updated the frontend yet. There is a tarball of models from a workshop a few weeks ago at [link](http://br.unchti.me/best.tar) and a generalized arabic model [here](http://br.unchti.me/arabic_generalized.mlmodel). Sorry for the inconvenience.

**Comment by msh2050** [comment]
thanks a lot..
it is working now in windows... although I get the error massage but I get the final result

for the error I think it is easy to be fixed 

(kraken) C:\Users\***\Desktop>kraken -i 1.jpg 111.txt binarize segment ocr -m arabic.mlmodel
Loading RNN default     ✓
Binarizing      ✓
Segmenting      ✓
Processing  [####################################]  100%
Writing recognition results for C:\Users\msh20\AppData\Local\Temp\tmpu8jzscow   ✓
Traceback (most recent call last):
  File "c:\users\****\anaconda3\envs\kraken\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\*****\anaconda3\envs\kraken\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\***\Anaconda3\envs\kraken\Scripts\kraken.exe\__main__.py", line 9, in <module>
  File "c:\users\**\anaconda3\envs\kraken\lib\site-packages\click\core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "c:\users\****\anaconda3\envs\kraken\lib\site-packages\click\core.py", line 717, in main
    rv = self.invoke(ctx)
  File "c:\users\***\anaconda3\envs\kraken\lib\site-packages\click\core.py", line 1164, in invoke
    return _process_result(rv)
  File "c:\users\***\anaconda3\envs\kraken\lib\site-packages\click\core.py", line 1102, in _process_result
    **ctx.params)
  File "c:\users\***\anaconda3\envs\kraken\lib\site-packages\click\core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "c:\users\***\anaconda3\envs\kraken\lib\site-packages\kraken\kraken.py", line 224, in process_pipeline
    os.unlink(f)
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\***\\AppData\\Local\\Temp\\tmpu8jzscow'

**Comment by msh2050** [comment]
for any one how may wont to try the (unsupported windows installation) you need to update the python to 3.6.7

regards
