### ISSUE TITLE
Installation errors 

### ISSUE THREAD

**Issue by terryBaz** [mittagessen/kraken#128]
**I'm struggling** with the `kraken` **installation for hours** (lets not say for days), first i tried it in windows10-64bit, then in anaconda, and finally i'm trying it on  linux.

- my setup
```
root@kali:~/Desktop# uname -a
Linux kali 4.3.0-kali1-amd64 #1 SMP Debian 4.3.3-7kali2 (2016-01-27) x86_64 GNU/Linux
```

```
root@kali:~/Desktop# conda info

     active environment : None
       user config file : /root/.condarc
 populated config files : 
          conda version : 4.6.7
    conda-build version : 3.17.6
         python version : 3.7.1.final.0
       base environment : /root/anaconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/linux-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /root/anaconda3/pkgs
                          /root/.conda/pkgs
       envs directories : /root/anaconda3/envs
                          /root/.conda/envs
               platform : linux-64
             user-agent : conda/4.6.7 requests/2.21.0 CPython/3.7.1 Linux/4.3.0-kali1-amd64 kali/2016.1 glibc/2.28
                UID:GID : 0:0
             netrc file : None
           offline mode : False
```

- the error

```
conda env create -f environment.yml
Collecting package metadata: done
Solving environment: done

Downloading and Extracting Packages
pip-19.0.3           | 1.8 MB    | ########################################## | 100% 
pytorch-cpu-1.0.1    | 26.8 MB   | ########################################## | 100% 
numpy-1.16.2         | 4.3 MB    | ########################################## | 100% 
bzip2-1.0.6          | 415 KB    | ########################################## | 100% 
pyrsistent-0.14.11   | 87 KB     | ########################################## | 100% 
certifi-2018.11.29   | 145 KB    | ########################################## | 100% 
cryptography-2.5     | 633 KB    | ########################################## | 100% 
urllib3-1.24.1       | 148 KB    | ########################################## | 100% 
future-0.17.1        | 700 KB    | ########################################## | 100% 
scipy-1.2.1          | 18.1 MB   | ########################################## | 100% 
openssl-1.1.1b       | 4.0 MB    | ########################################## | 100% 
regex-2019.02.21     | 351 KB    | ########################################## | 100% 
pyopenssl-19.0.0     | 81 KB     | ########################################## | 100% 
requests-2.21.0      | 84 KB     | ########################################## | 100% 
jsonschema-3.0.1     | 85 KB     | ########################################## | 100% 
python-3.7.1         | 36.4 MB   | ########################################## | 100% 
chardet-3.0.4        | 167 KB    | ########################################## | 100% 
six-1.12.0           | 22 KB     | ########################################## | 100% 
cffi-1.12.2          | 217 KB    | ########################################## | 100% 
pillow-5.4.1         | 605 KB    | ########################################## | 100% 
protobuf-3.7.0       | 651 KB    | ########################################## | 100% 
pysocks-1.6.8        | 22 KB     | ########################################## | 100% 
markupsafe-1.1.1     | 26 KB     | ########################################## | 100% 
setuptools-40.8.0    | 625 KB    | ########################################## | 100% 
wheel-0.33.1         | 34 KB     | ########################################## | 100% 
lxml-4.3.2           | 1.5 MB    | ########################################## | 100% 
asn1crypto-0.24.0    | 154 KB    | ########################################## | 100% 
idna-2.8             | 100 KB    | ########################################## | 100% 
Preparing transaction: done
Verifying transaction: done
Executing transaction: done

CondaEnvException: Pip subcommand failed with 
output: Collecting git+https://github.com/mittagessen/kraken.git@master (from -r /root/Desktop/condaenv.6xddsfrt.requirements.txt (line 2))
  Cloning https://github.com/mittagessen/kraken.git (to revision master) to /tmp/pip-req-build-yehr_s7a
git : 'credential-' n'est pas une commande git. Voir 'git --help'.

Vouliez-vous dire cela ?
	credential
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/root/anaconda3/envs/kraken/lib/python3.7/tokenize.py", line 447, in open
        buffer = _builtin_open(filename, 'rb')
    FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-req-build-yehr_s7a/setup.py'
    
    ----------------------------------------

error: ++ /root/anaconda3/bin/conda shell.posix hook
+ eval 'export CONDA_EXE="/root/anaconda3/bin/conda"
# Copyright (C) 2012 Anaconda, Inc
# SPDX-License-Identifier: BSD-3-Clause

__conda_hashr() {
    if [ -n "${ZSH_VERSION:+x}" ]; then
        \rehash
    elif [ -n "${POSH_VERSION:+x}" ]; then
        :  # pass
    else
        \hash -r
    fi
}

__conda_activate() {
    if [ -n "${CONDA_PS1_BACKUP:+x}" ]; then
        # Handle transition from shell activated with conda <= 4.3 to a subsequent activation
        # after conda updated to >= 4.4. See issue #6173.
        PS1="$CONDA_PS1_BACKUP"
        \unset CONDA_PS1_BACKUP
    fi

    \local cmd="$1"
    shift
    \local ask_conda
    ask_conda="$(PS1="$PS1" "$CONDA_EXE" shell.posix "$cmd" "$@")" || \return $?
    \eval "$ask_conda"
    __conda_hashr
}

__conda_reactivate() {
    \local ask_conda
    ask_conda="$(PS1="$PS1" "$CONDA_EXE" shell.posix reactivate)" || \return $?
    \eval "$ask_conda"
    __conda_hashr
}

conda() {
    if [ "$#" -lt 1 ]; then
        "$CONDA_EXE"
    else
        \local cmd="$1"
        shift
        case "$cmd" in
            activate|deactivate)
                __conda_activate "$cmd" "$@"
                ;;
            install|update|upgrade|remove|uninstall)
                "$CONDA_EXE" "$cmd" "$@" && __conda_reactivate
                ;;
            *) "$CONDA_EXE" "$cmd" "$@" ;;
        esac
    fi
}

if [ -z "${CONDA_SHLVL+x}" ]; then
    \export CONDA_SHLVL=0
    PATH="$(dirname "$(dirname "$CONDA_EXE")")/condabin:${PATH:-}"
    \export PATH

    # We'\''re not allowing PS1 to be unbound. It must at least be set.
    # However, we'\''re not exporting it, which can cause problems when starting a second shell
    # via a first shell (i.e. starting zsh from bash).
    if [ -z "${PS1+x}" ]; then
        PS1=
    fi
fi


conda activate base'
++ export CONDA_EXE=/root/anaconda3/bin/conda
++ CONDA_EXE=/root/anaconda3/bin/conda
++ '[' -z '' ']'
++ export CONDA_SHLVL=0
++ CONDA_SHLVL=0
++++ dirname /root/anaconda3/bin/conda
+++ dirname /root/anaconda3/bin
++ PATH=/root/anaconda3/condabin:/root/anaconda3/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
++ export PATH
++ '[' -z '' ']'
++ PS1=
++ conda activate base
++ '[' 2 -lt 1 ']'
++ local cmd=activate
++ shift
++ case "$cmd" in
++ __conda_activate activate base
++ '[' -n '' ']'
++ local cmd=activate
++ shift
++ local ask_conda
+++ PS1=
+++ /root/anaconda3/bin/conda shell.posix activate base
++ ask_conda='PS1='\''(base) '\''
\export CONDA_DEFAULT_ENV='\''base'\''
\export CONDA_EXE='\''/root/anaconda3/bin/conda'\''
\export CONDA_PREFIX='\''/root/anaconda3'\''
\export CONDA_PROMPT_MODIFIER='\''(base) '\''
\export CONDA_PYTHON_EXE='\''/root/anaconda3/bin/python'\''
\export CONDA_SHLVL='\''1'\''
\export PATH='\''/root/anaconda3/bin:/root/anaconda3/condabin:/root/anaconda3/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'\'''
++ eval 'PS1='\''(base) '\''
\export CONDA_DEFAULT_ENV='\''base'\''
\export CONDA_EXE='\''/root/anaconda3/bin/conda'\''
\export CONDA_PREFIX='\''/root/anaconda3'\''
\export CONDA_PROMPT_MODIFIER='\''(base) '\''
\export CONDA_PYTHON_EXE='\''/root/anaconda3/bin/python'\''
\export CONDA_SHLVL='\''1'\''
\export PATH='\''/root/anaconda3/bin:/root/anaconda3/condabin:/root/anaconda3/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'\'''
+++ PS1='(base) '
+++ export CONDA_DEFAULT_ENV=base
+++ CONDA_DEFAULT_ENV=base
+++ export CONDA_EXE=/root/anaconda3/bin/conda
+++ CONDA_EXE=/root/anaconda3/bin/conda
+++ export CONDA_PREFIX=/root/anaconda3
+++ CONDA_PREFIX=/root/anaconda3
+++ export 'CONDA_PROMPT_MODIFIER=(base) '
+++ CONDA_PROMPT_MODIFIER='(base) '
+++ export CONDA_PYTHON_EXE=/root/anaconda3/bin/python
+++ CONDA_PYTHON_EXE=/root/anaconda3/bin/python
+++ export CONDA_SHLVL=1
+++ CONDA_SHLVL=1
+++ export PATH=/root/anaconda3/bin:/root/anaconda3/condabin:/root/anaconda3/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
+++ PATH=/root/anaconda3/bin:/root/anaconda3/condabin:/root/anaconda3/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
++ __conda_hashr
++ '[' -n '' ']'
++ '[' -n '' ']'
++ hash -r
+ conda activate /root/anaconda3/envs/kraken
+ '[' 2 -lt 1 ']'
+ local cmd=activate
+ shift
+ case "$cmd" in
+ __conda_activate activate /root/anaconda3/envs/kraken
+ '[' -n '' ']'
+ local cmd=activate
+ shift
+ local ask_conda
++ PS1='(base) '
++ /root/anaconda3/bin/conda shell.posix activate /root/anaconda3/envs/kraken
+ ask_conda='PS1='\''(kraken) '\''
\export CONDA_DEFAULT_ENV='\''kraken'\''
\export CONDA_PREFIX='\''/root/anaconda3/envs/kraken'\''
\export CONDA_PREFIX_1='\''/root/anaconda3'\''
\export CONDA_PROMPT_MODIFIER='\''(kraken) '\''
\export CONDA_SHLVL='\''2'\''
\export PATH='\''/root/anaconda3/envs/kraken/bin:/root/anaconda3/condabin:/root/anaconda3/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'\'''
+ eval 'PS1='\''(kraken) '\''
\export CONDA_DEFAULT_ENV='\''kraken'\''
\export CONDA_PREFIX='\''/root/anaconda3/envs/kraken'\''
\export CONDA_PREFIX_1='\''/root/anaconda3'\''
\export CONDA_PROMPT_MODIFIER='\''(kraken) '\''
\export CONDA_SHLVL='\''2'\''
\export PATH='\''/root/anaconda3/envs/kraken/bin:/root/anaconda3/condabin:/root/anaconda3/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'\'''
++ PS1='(kraken) '
++ export CONDA_DEFAULT_ENV=kraken
++ CONDA_DEFAULT_ENV=kraken
++ export CONDA_PREFIX=/root/anaconda3/envs/kraken
++ CONDA_PREFIX=/root/anaconda3/envs/kraken
++ export CONDA_PREFIX_1=/root/anaconda3
++ CONDA_PREFIX_1=/root/anaconda3
++ export 'CONDA_PROMPT_MODIFIER=(kraken) '
++ CONDA_PROMPT_MODIFIER='(kraken) '
++ export CONDA_SHLVL=2
++ CONDA_SHLVL=2
++ export PATH=/root/anaconda3/envs/kraken/bin:/root/anaconda3/condabin:/root/anaconda3/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
++ PATH=/root/anaconda3/envs/kraken/bin:/root/anaconda3/condabin:/root/anaconda3/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
+ __conda_hashr
+ '[' -n '' ']'
+ '[' -n '' ']'
+ hash -r
+ pip install -r /root/Desktop/condaenv.6xddsfrt.requirements.txt
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-req-build-yehr_s7a/
```

**Comment by mittagessen** [comment]
I've got no idea where that anaconda/pip error is coming from, especially as there's not a single call to `credential-`-anything in pip nor conda and I can't reproduce it. Does just running

```
$ git clone https://github.com/mittagessen/kraken.git
```

work on your machine? There seems to be a more fundamental issue with git.

**Comment by terryBaz** [comment]
thanks @mittagessen, you were right I had a problem with my `git config` **but even after** fixing it I'm getting this: 

```
conda env create -f environment.yml
Collecting package metadata: done
Solving environment: done
Preparing transaction: done
Verifying transaction: done
Executing transaction: done


CondaEnvException: Pip subcommand failed with 
output: Collecting git+https://github.com/mittagessen/kraken.git@master (from -r /root/Desktop/condaenv.epxumxdw.requirements.txt (line 2))
  Cloning https://github.com/mittagessen/kraken.git (to revision master) to /tmp/pip-req-build-y4q1zqcl
error: RPC failed; result=18, HTTP code = 200
fatal: The remote end hung up unexpectedly
fatal: fin de fichier prématurée
fatal: index-pack failed

error: ++ /root/anaconda3/bin/conda shell.posix hook
+ eval 'export CONDA_EXE="/root/anaconda3/bin/conda"
# Copyright (C) 2012 Anaconda, Inc
# SPDX-License-Identifier: BSD-3-Clause

__conda_hashr() {
    if [ -n "${ZSH_VERSION:+x}" ]; then
        \rehash
    elif [ -n "${POSH_VERSION:+x}" ]; then
        :  # pass
    else
        \hash -r
    fi
}

__conda_activate() {
    if [ -n "${CONDA_PS1_BACKUP:+x}" ]; then
        # Handle transition from shell activated with conda <= 4.3 to a subsequent activation
        # after conda updated to >= 4.4. See issue #6173.
        PS1="$CONDA_PS1_BACKUP"
        \unset CONDA_PS1_BACKUP
    fi

    \local cmd="$1"
    shift
    \local ask_conda
    ask_conda="$(PS1="$PS1" "$CONDA_EXE" shell.posix "$cmd" "$@")" || \return $?
    \eval "$ask_conda"
    __conda_hashr
}

__conda_reactivate() {
    \local ask_conda
    ask_conda="$(PS1="$PS1" "$CONDA_EXE" shell.posix reactivate)" || \return $?
    \eval "$ask_conda"
    __conda_hashr
}

conda() {
    if [ "$#" -lt 1 ]; then
        "$CONDA_EXE"
    else
        \local cmd="$1"
        shift
        case "$cmd" in
            activate|deactivate)
                __conda_activate "$cmd" "$@"
                ;;
            install|update|upgrade|remove|uninstall)
                "$CONDA_EXE" "$cmd" "$@" && __conda_reactivate
                ;;
            *) "$CONDA_EXE" "$cmd" "$@" ;;
        esac
    fi
}

if [ -z "${CONDA_SHLVL+x}" ]; then
    \export CONDA_SHLVL=0
    PATH="$(dirname "$(dirname "$CONDA_EXE")")/condabin:${PATH:-}"
    \export PATH

    # We'\''re not allowing PS1 to be unbound. It must at least be set.
    # However, we'\''re not exporting it, which can cause problems when starting a second shell
    # via a first shell (i.e. starting zsh from bash).
    if [ -z "${PS1+x}" ]; then
        PS1=
    fi
fi


conda activate base'
++ export CONDA_EXE=/root/anaconda3/bin/conda
++ CONDA_EXE=/root/anaconda3/bin/conda
++ '[' -z '' ']'
++ export CONDA_SHLVL=0
++ CONDA_SHLVL=0
++++ dirname /root/anaconda3/bin/conda
+++ dirname /root/anaconda3/bin
++ PATH=/root/anaconda3/condabin:/root/anaconda3/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
++ export PATH
++ '[' -z '' ']'
++ PS1=
++ conda activate base
++ '[' 2 -lt 1 ']'
++ local cmd=activate
++ shift
++ case "$cmd" in
++ __conda_activate activate base
++ '[' -n '' ']'
++ local cmd=activate
++ shift
++ local ask_conda
+++ PS1=
+++ /root/anaconda3/bin/conda shell.posix activate base
++ ask_conda='PS1='\''(base) '\''
\export CONDA_DEFAULT_ENV='\''base'\''
\export CONDA_EXE='\''/root/anaconda3/bin/conda'\''
\export CONDA_PREFIX='\''/root/anaconda3'\''
\export CONDA_PROMPT_MODIFIER='\''(base) '\''
\export CONDA_PYTHON_EXE='\''/root/anaconda3/bin/python'\''
\export CONDA_SHLVL='\''1'\''
\export PATH='\''/root/anaconda3/bin:/root/anaconda3/condabin:/root/anaconda3/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'\'''
++ eval 'PS1='\''(base) '\''
\export CONDA_DEFAULT_ENV='\''base'\''
\export CONDA_EXE='\''/root/anaconda3/bin/conda'\''
\export CONDA_PREFIX='\''/root/anaconda3'\''
\export CONDA_PROMPT_MODIFIER='\''(base) '\''
\export CONDA_PYTHON_EXE='\''/root/anaconda3/bin/python'\''
\export CONDA_SHLVL='\''1'\''
\export PATH='\''/root/anaconda3/bin:/root/anaconda3/condabin:/root/anaconda3/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'\'''
+++ PS1='(base) '
+++ export CONDA_DEFAULT_ENV=base
+++ CONDA_DEFAULT_ENV=base
+++ export CONDA_EXE=/root/anaconda3/bin/conda
+++ CONDA_EXE=/root/anaconda3/bin/conda
+++ export CONDA_PREFIX=/root/anaconda3
+++ CONDA_PREFIX=/root/anaconda3
+++ export 'CONDA_PROMPT_MODIFIER=(base) '
+++ CONDA_PROMPT_MODIFIER='(base) '
+++ export CONDA_PYTHON_EXE=/root/anaconda3/bin/python
+++ CONDA_PYTHON_EXE=/root/anaconda3/bin/python
+++ export CONDA_SHLVL=1
+++ CONDA_SHLVL=1
+++ export PATH=/root/anaconda3/bin:/root/anaconda3/condabin:/root/anaconda3/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
+++ PATH=/root/anaconda3/bin:/root/anaconda3/condabin:/root/anaconda3/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
++ __conda_hashr
++ '[' -n '' ']'
++ '[' -n '' ']'
++ hash -r
+ conda activate /root/anaconda3/envs/kraken
+ '[' 2 -lt 1 ']'
+ local cmd=activate
+ shift
+ case "$cmd" in
+ __conda_activate activate /root/anaconda3/envs/kraken
+ '[' -n '' ']'
+ local cmd=activate
+ shift
+ local ask_conda
++ PS1='(base) '
++ /root/anaconda3/bin/conda shell.posix activate /root/anaconda3/envs/kraken
+ ask_conda='PS1='\''(kraken) '\''
\export CONDA_DEFAULT_ENV='\''kraken'\''
\export CONDA_PREFIX='\''/root/anaconda3/envs/kraken'\''
\export CONDA_PREFIX_1='\''/root/anaconda3'\''
\export CONDA_PROMPT_MODIFIER='\''(kraken) '\''
\export CONDA_SHLVL='\''2'\''
\export PATH='\''/root/anaconda3/envs/kraken/bin:/root/anaconda3/condabin:/root/anaconda3/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'\'''
+ eval 'PS1='\''(kraken) '\''
\export CONDA_DEFAULT_ENV='\''kraken'\''
\export CONDA_PREFIX='\''/root/anaconda3/envs/kraken'\''
\export CONDA_PREFIX_1='\''/root/anaconda3'\''
\export CONDA_PROMPT_MODIFIER='\''(kraken) '\''
\export CONDA_SHLVL='\''2'\''
\export PATH='\''/root/anaconda3/envs/kraken/bin:/root/anaconda3/condabin:/root/anaconda3/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'\'''
++ PS1='(kraken) '
++ export CONDA_DEFAULT_ENV=kraken
++ CONDA_DEFAULT_ENV=kraken
++ export CONDA_PREFIX=/root/anaconda3/envs/kraken
++ CONDA_PREFIX=/root/anaconda3/envs/kraken
++ export CONDA_PREFIX_1=/root/anaconda3
++ CONDA_PREFIX_1=/root/anaconda3
++ export 'CONDA_PROMPT_MODIFIER=(kraken) '
++ CONDA_PROMPT_MODIFIER='(kraken) '
++ export CONDA_SHLVL=2
++ CONDA_SHLVL=2
++ export PATH=/root/anaconda3/envs/kraken/bin:/root/anaconda3/condabin:/root/anaconda3/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
++ PATH=/root/anaconda3/envs/kraken/bin:/root/anaconda3/condabin:/root/anaconda3/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
+ __conda_hashr
+ '[' -n '' ']'
+ '[' -n '' ']'
+ hash -r
+ pip install -r /root/Desktop/condaenv.epxumxdw.requirements.txt
Command "git clone -q https://github.com/mittagessen/kraken.git /tmp/pip-req-build-y4q1zqcl" failed with error code 128 in None
```

- Another thing, I'm wondering why `conda install -c mittagessen kraken` is not working !
