### ISSUE TITLE
installation error 

### ISSUE THREAD

**Issue by hassan5544** [mittagessen/kraken#149]
I am new to use Kraken ocr , i am using Linux ubuntu 
when I try to install the Kraken using conda the installation complete but when I run the Kraken the shell says the Kraken command not found also for the pip3 install Kraken 
When i use pip3 install . using the git repository file i get the following error 

ERROR:root:Error parsing
Traceback (most recent call last):
  File "/home/hassan/Desktop/kraken-master/.eggs/pbr-5.4.2-py3.7.egg/pbr/core.py", line 96, in pbr
    attrs = util.cfg_to_args(path, dist.script_args)
  File "/home/hassan/Desktop/kraken-master/.eggs/pbr-5.4.2-py3.7.egg/pbr/util.py", line 270, in cfg_to_args
    pbr.hooks.setup_hook(config)
  File "/home/hassan/Desktop/kraken-master/.eggs/pbr-5.4.2-py3.7.egg/pbr/hooks/__init__.py", line 25, in setup_hook
    metadata_config.run()
  File "/home/hassan/Desktop/kraken-master/.eggs/pbr-5.4.2-py3.7.egg/pbr/hooks/base.py", line 27, in run
    self.hook()
  File "/home/hassan/Desktop/kraken-master/.eggs/pbr-5.4.2-py3.7.egg/pbr/hooks/metadata.py", line 26, in hook
    self.config['name'], self.config.get('version', None))
  File "/home/hassan/Desktop/kraken-master/.eggs/pbr-5.4.2-py3.7.egg/pbr/packaging.py", line 874, in get_version
    name=package_name))
Exception: Versioning for this project requires either an sdist tarball, or access to an upstream git repository. It's also possible that there is a mismatch between the package name in setup.cfg and the argument given to pbr.version.VersionInfo. Project name kraken was given, but was not able to be found.
error in setup command: Error parsing /home/hassan/Desktop/kraken-master/setup.cfg: Exception: Versioning for this project requires either an sdist tarball, or access to an upstream git repository. It's also possible that there is a mismatch between the package name in setup.cfg and the argument given to pbr.version.VersionInfo. Project name kraken was given, but was not able to be found.

can you please help me I am struggling for hours

**Comment by mittagessen** [comment]
I don't know what's happening and I suspect you've already solved the issue but it seems you're running on python 3.7 which isn't supported yet (coreml still hasn't packaged for 3.7). Downgrade to 3.6 and see if that works.
