### ISSUE TITLE
`kraken list` seems to fail

### ISSUE THREAD

**Issue by poke1024** [mittagessen/kraken#156]
My installation might be wrong, but this looks like a server error?

```
(kraken) nbliebl:kraken liebl$ kraken list
Retrieving model list ..Traceback (most recent call last):
  File "/Users/liebl/anaconda3/envs/kraken/bin/kraken", line 10, in <module>
    sys.exit(cli())
  File "/Users/liebl/anaconda3/envs/kraken/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/Users/liebl/anaconda3/envs/kraken/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/Users/liebl/anaconda3/envs/kraken/lib/python3.6/site-packages/click/core.py", line 1163, in invoke
    rv.append(sub_ctx.command.invoke(sub_ctx))
  File "/Users/liebl/anaconda3/envs/kraken/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/liebl/anaconda3/envs/kraken/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/Users/liebl/anaconda3/envs/kraken/lib/python3.6/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/liebl/anaconda3/envs/kraken/lib/python3.6/site-packages/kraken/kraken.py", line 421, in list_models
    model_list = repo.get_listing(partial(message, '.', nl=False))
  File "/Users/liebl/anaconda3/envs/kraken/lib/python3.6/site-packages/kraken/repo.py", line 230, in get_listing
    r.raise_for_status()
  File "/Users/liebl/anaconda3/envs/kraken/lib/python3.6/site-packages/requests/models.py", line 893, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: INTERNAL SERVER ERROR for url: https://zenodo.org/api/files/51670ea2-5138-4023-927d-c40900083357/metadata.json
```

**Comment by mittagessen** [comment]
This seems to be an intermittent error on zenodo's side. I just ran it 10 times and it failed once. I'll wait a few days and see if it is just something load related and if it doesn't go away I'll open a bug report.

Just run the command again in the meanwhile.
