### ISSUE TITLE
Too many open files error in batch segmentation

### ISSUE THREAD

**Issue by bencomp** [mittagessen/kraken#165]
When I ran segmentation on a directory of 600+ images, after processing for a while kraken exited with this:

```
Traceback (most recent call last):
  File "/Users/companjenba/virtualenvs/kraken/lib/python3.7/site-packages/kraken/kraken.py", line 53, in binarizer
  File "/Users/companjenba/virtualenvs/kraken/lib/python3.7/site-packages/PIL/Image.py", line 2766, in open
OSError: [Errno 24] Too many open files: 'Radloff-1885-v2.jpg/Radloff-1885-v2 - 0517.jpg'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/companjenba/virtualenvs/kraken/lib/python3.7/site-packages/click/core.py", line 717, in main
  File "/Users/companjenba/virtualenvs/kraken/lib/python3.7/site-packages/click/core.py", line 1164, in invoke
  File "/Users/companjenba/virtualenvs/kraken/lib/python3.7/site-packages/click/core.py", line 1102, in _process_result
  File "/Users/companjenba/virtualenvs/kraken/lib/python3.7/site-packages/click/core.py", line 555, in invoke
  File "/Users/companjenba/virtualenvs/kraken/lib/python3.7/site-packages/kraken/kraken.py", line 225, in process_pipeline
  File "/Users/companjenba/virtualenvs/kraken/lib/python3.7/site-packages/kraken/kraken.py", line 55, in binarizer
click.exceptions.BadParameter: [Errno 24] Too many open files: 'Radloff-1885-v2.jpg/Radloff-1885-v2 - 0517.jpg'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/companjenba/virtualenvs/kraken/bin/kraken", line 10, in <module>
  File "/Users/companjenba/virtualenvs/kraken/lib/python3.7/site-packages/click/core.py", line 764, in __call__
  File "/Users/companjenba/virtualenvs/kraken/lib/python3.7/site-packages/click/core.py", line 734, in main
  File "/Users/companjenba/virtualenvs/kraken/lib/python3.7/site-packages/click/exceptions.py", line 69, in show
  File "/Users/companjenba/virtualenvs/kraken/lib/python3.7/site-packages/click/core.py", line 510, in get_usage
  File "/Users/companjenba/virtualenvs/kraken/lib/python3.7/site-packages/click/core.py", line 820, in get_usage
  File "/Users/companjenba/virtualenvs/kraken/lib/python3.7/site-packages/click/core.py", line 833, in format_usage
  File "/Users/companjenba/virtualenvs/kraken/lib/python3.7/site-packages/click/formatting.py", line 140, in write_usage
  File "/Users/companjenba/virtualenvs/kraken/lib/python3.7/site-packages/click/formatting.py", line 45, in wrap_text
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 859, in get_code
  File "<frozen importlib._bootstrap_external>", line 916, in get_data
OSError: [Errno 24] Too many open files: '/Users/companjenba/virtualenvs/kraken/lib/python3.7/site-packages/click/_textwrap.py'
```

From my initial investigation, it looks like the calls to PIL's `Image.open()` never close the files.
<https://stackoverflow.com/questions/31751464/how-do-i-close-an-image-opened-in-pillow> explains that it's possible to use a `with` block to automatically close the file after use.

**Comment by mittagessen** [comment]
> From my initial investigation, it looks like the calls to PIL's `Image.open()` never close the files.
> <https://stackoverflow.com/questions/31751464/how-do-i-close-an-image-opened-in-pillow> explains that it's possible to use a `with` block to automatically close the file after use.

I don't think PIL is the source of this error as the library closes the
file descriptor as soon as the image data is read and they are processed
serially here. On the other hand we're leaking file descriptors in the
pipeline processing which is most likely the actual culprit. 

I'll push a fix into a separate branch (fd_leak_165) in a second. If you
could test if it works for you I'd be grateful.

**Comment by bencomp** [comment]
Thanks for the quick response. I'll try to test it.

I wonder, though, if the files are closed in the correct place. When I use Activity Monitor (on Mac) and watch the process, the temporary files are opened at the time of processing (I guess through `Image.open(file_path)`), but not closed after processing. Your commit https://github.com/mittagessen/kraken/commit/56e8078ad2adc4c4d5d385244142f3c4b28b89dd appears to close the files earlier in the process. I don't have much experience with Click and the Kraken pipeline, so I may be wrong. I'll try anyway :)

**Comment by mittagessen** [comment]
> I wonder, though, if the files are closed in the correct place. When I
> use Activity Monitor (on Mac) and watch the process, the temporary
> files are opened at the time of processing (I guess through
> `Image.open(file_path)`), but not closed after processing.

mkstemp() returns both a path and a fd. I can't use the fd at the time
of creation though so the patch closes the file descriptor immediately
and only opens it during processing again. That's actually a minor
security issue as somebody could replace the temporary files between
creation and use. Previously kraken just ignored the open fd which
caused them to leak until you ran out of fds causing a crash.

When opening an image file with PIL the file isn't read but only opened,
i.e. an fd is allocated. Once any kind of operation is done on the
object the contents are read, processed, and the fd closed automatically
afterwards. On Linux this happens without issues but I don't have access
to a Mac OS X machine. If you can send me some log that confirms the
issue, I'll add explicit closing to image files.
