### ISSUE TITLE
install fails on ppc64le

### ISSUE THREAD

**Issue by Shreeshrii** [mittagessen/kraken#171]
```
ubuntu@tesseract-ocr:~$ conda env create -f environment.yml
Collecting package metadata (repodata.json): done
Solving environment: done
Preparing transaction: done
Verifying transaction: done
Executing transaction: done
Ran pip subprocess with arguments:
['/home/ubuntu/anaconda3/envs/kraken/bin/python', '-m', 'pip', 'install', '-U', '-r', '/home/ubuntu/condaenv.zt_5qyhz.requirements.txt']
Pip subprocess output:
Collecting git+https://github.com/mittagessen/kraken.git@master (from -r /home/ubuntu/condaenv.zt_5qyhz.requirements.txt (line 1))
  Cloning https://github.com/mittagessen/kraken.git (to revision master) to /tmp/pip-req-build-4oqhw774
Requirement already satisfied, skipping upgrade: jsonschema in ./anaconda3/envs/kraken/lib/python3.7/site-packages (from kraken==2.0.8->-r /home/ubuntu/condaenv.zt_5qyhz.requirements.txt (line 1)) (3.2.0)
Requirement already satisfied, skipping upgrade: lxml in ./anaconda3/envs/kraken/lib/python3.7/site-packages (from kraken==2.0.8->-r /home/ubuntu/condaenv.zt_5qyhz.requirements.txt (line 1)) (4.5.0)
Requirement already satisfied, skipping upgrade: future in ./anaconda3/envs/kraken/lib/python3.7/site-packages (from kraken==2.0.8->-r /home/ubuntu/condaenv.zt_5qyhz.requirements.txt (line 1)) (0.17.1)
Requirement already satisfied, skipping upgrade: requests in ./anaconda3/envs/kraken/lib/python3.7/site-packages (from kraken==2.0.8->-r /home/ubuntu/condaenv.zt_5qyhz.requirements.txt (line 1)) (2.22.0)
Requirement already satisfied, skipping upgrade: click>=7.0 in ./anaconda3/envs/kraken/lib/python3.7/site-packages (from kraken==2.0.8->-r /home/ubuntu/condaenv.zt_5qyhz.requirements.txt (line 1)) (7.0)
Requirement already satisfied, skipping upgrade: numpy in ./anaconda3/envs/kraken/lib/python3.7/site-packages (from kraken==2.0.8->-r /home/ubuntu/condaenv.zt_5qyhz.requirements.txt (line 1)) (1.16.6)
Requirement already satisfied, skipping upgrade: Pillow in ./anaconda3/envs/kraken/lib/python3.7/site-packages (from kraken==2.0.8->-r /home/ubuntu/condaenv.zt_5qyhz.requirements.txt (line 1)) (6.2.1)
Requirement already satisfied, skipping upgrade: regex in ./anaconda3/envs/kraken/lib/python3.7/site-packages (from kraken==2.0.8->-r /home/ubuntu/condaenv.zt_5qyhz.requirements.txt (line 1)) (2019.12.9)
Requirement already satisfied, skipping upgrade: scipy in ./anaconda3/envs/kraken/lib/python3.7/site-packages (from kraken==2.0.8->-r /home/ubuntu/condaenv.zt_5qyhz.requirements.txt (line 1)) (1.3.1)
Requirement already satisfied, skipping upgrade: protobuf>=3.0.0 in ./anaconda3/envs/kraken/lib/python3.7/site-packages (from kraken==2.0.8->-r /home/ubuntu/condaenv.zt_5qyhz.requirements.txt (line 1)) (3.8.0)
Requirement already satisfied, skipping upgrade: jinja2 in ./anaconda3/envs/kraken/lib/python3.7/site-packages (from kraken==2.0.8->-r /home/ubuntu/condaenv.zt_5qyhz.requirements.txt (line 1)) (2.11.1)
Requirement already satisfied, skipping upgrade: python-bidi in ./anaconda3/envs/kraken/lib/python3.7/site-packages (from kraken==2.0.8->-r /home/ubuntu/condaenv.zt_5qyhz.requirements.txt (line 1)) (0.4.2)
Requirement already satisfied, skipping upgrade: torchvision in ./anaconda3/envs/kraken/lib/python3.7/site-packages (from kraken==2.0.8->-r /home/ubuntu/condaenv.zt_5qyhz.requirements.txt (line 1)) (0.4.0a0)
Requirement already satisfied, skipping upgrade: torch>=1.0.0 in ./anaconda3/envs/kraken/lib/python3.7/site-packages (from kraken==2.0.8->-r /home/ubuntu/condaenv.zt_5qyhz.requirements.txt (line 1)) (1.2.0)

Pip subprocess error:
  Running command git clone -q https://github.com/mittagessen/kraken.git /tmp/pip-req-build-4oqhw774
ERROR: Could not find a version that satisfies the requirement coremltools (from kraken==2.0.8->-r /home/ubuntu/condaenv.zt_5qyhz.requirements.txt (line 1)) (from versions: none)
ERROR: No matching distribution found for coremltools (from kraken==2.0.8->-r /home/ubuntu/condaenv.zt_5qyhz.requirements.txt (line 1))


CondaEnvException: Pip failed
```

Are `coremltools` required for running training? I am using Ubuntu on IBM Power8. I wanted to test kraken training for Devanagari script.

**Comment by mittagessen** [comment]
You need coremltools for the model serialization/deserialization so it
is rather essential. The problem stems from the coreml developers not
pushing a source tarball to pypi but only the x86 wheels. The easiest
way would be to install it from
[source](https://github.com/apple/coremltools) although I can't
garantuee that this will be a pleasant experience on an exotic platform
like Power8.

**Comment by Shreeshrii** [comment]
Thanks. I will give it a try.

Are there any existing kraken models for Devanagari script?

**Comment by mittagessen** [comment]
> Are there any existing kraken models for Devanagari script?

Nope. If you've got existing training data you can use it to retrain a
model obviously but as far as I know nobody's trained on yet.

**Comment by Shreeshrii** [comment]
I installed coremltools and kraken again under conda now.

```
(py36) ubuntu@tesseract-ocr:~$ sudo pip install kraken
WARNING: The directory '/home/ubuntu/.cache/pip' or its parent directory is not owned or is not writable by the current user. The cache has been disabled. Check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting kraken
  Downloading kraken-2.0.8-py3-none-any.whl (643 kB)
     |████████████████████████████████| 643 kB 2.0 MB/s
Requirement already satisfied: numpy in ./anaconda3/envs/py36/lib/python3.6/site-packages (from kraken) (1.16.6)
Requirement already satisfied: coremltools in ./anaconda3/envs/py36/lib/python3.6/site-packages (from kraken) (3.1)
Requirement already satisfied: future in ./.local/lib/python3.6/site-packages (from kraken) (0.17.1)
Requirement already satisfied: scipy in ./anaconda3/envs/py36/lib/python3.6/site-packages (from kraken) (1.3.1)
Requirement already satisfied: torchvision in ./anaconda3/envs/py36/lib/python3.6/site-packages (from kraken) (0.4.0a0)
Requirement already satisfied: torch>=1.0.0 in ./anaconda3/envs/py36/lib/python3.6/site-packages (from kraken) (1.2.0)
Requirement already satisfied: click>=7.0 in ./anaconda3/envs/py36/lib/python3.6/site-packages (from kraken) (7.0)
Requirement already satisfied: Pillow in ./anaconda3/envs/py36/lib/python3.6/site-packages (from kraken) (6.2.1)
Requirement already satisfied: python-bidi in ./anaconda3/envs/py36/lib/python3.6/site-packages (from kraken) (0.4.2)
Requirement already satisfied: jsonschema in ./anaconda3/envs/py36/lib/python3.6/site-packages (from kraken) (3.2.0)
Requirement already satisfied: requests in ./anaconda3/envs/py36/lib/python3.6/site-packages (from kraken) (2.22.0)
Requirement already satisfied: lxml in ./anaconda3/envs/py36/lib/python3.6/site-packages (from kraken) (4.5.0)
Requirement already satisfied: regex in ./anaconda3/envs/py36/lib/python3.6/site-packages (from kraken) (2020.1.8)
Requirement already satisfied: protobuf>=3.0.0 in ./anaconda3/envs/py36/lib/python3.6/site-packages (from kraken) (3.8.0)
Requirement already satisfied: jinja2 in ./anaconda3/envs/py36/lib/python3.6/site-packages (from kraken) (2.11.1)
Requirement already satisfied: six>=1.10.0 in ./anaconda3/envs/py36/lib/python3.6/site-packages (from coremltools->kraken) (1.12.0)
Requirement already satisfied: pyrsistent>=0.14.0 in ./anaconda3/envs/py36/lib/python3.6/site-packages (from jsonschema->kraken) (0.15.7)
Requirement already satisfied: attrs>=17.4.0 in ./anaconda3/envs/py36/lib/python3.6/site-packages (from jsonschema->kraken) (19.3.0)
Requirement already satisfied: importlib-metadata; python_version < "3.8" in ./anaconda3/envs/py36/lib/python3.6/site-packages (from jsonschema->kraken) (1.5.0)
Requirement already satisfied: setuptools in ./anaconda3/envs/py36/lib/python3.6/site-packages (from jsonschema->kraken) (45.2.0.post20200210)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in ./anaconda3/envs/py36/lib/python3.6/site-packages (from requests->kraken) (3.0.4)
Requirement already satisfied: idna<2.9,>=2.5 in ./anaconda3/envs/py36/lib/python3.6/site-packages (from requests->kraken) (2.8)
Requirement already satisfied: certifi>=2017.4.17 in ./anaconda3/envs/py36/lib/python3.6/site-packages (from requests->kraken) (2019.11.28)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in ./anaconda3/envs/py36/lib/python3.6/site-packages (from requests->kraken) (1.25.8)
Requirement already satisfied: MarkupSafe>=0.23 in ./anaconda3/envs/py36/lib/python3.6/site-packages (from jinja2->kraken) (1.1.1)
Requirement already satisfied: zipp>=0.5 in ./anaconda3/envs/py36/lib/python3.6/site-packages (from importlib-metadata; python_version < "3.8"->jsonschema->kraken) (2.2.0)
Installing collected packages: kraken
Successfully installed kraken-2.0.8
```

While the package is sucessfully installed, I am getting an error running linegen (this worked earlier outside of conda).

```
(py36) ubuntu@tesseract-ocr:~$ cd  kraken/tests/resources
(py36) ubuntu@tesseract-ocr:~/kraken/tests/resources$ ketos linegen -ur NFC -u NFD -n 15  --disable-degradation   -f Siddhanta test.txt
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/py36/bin/ketos", line 8, in <module>
    sys.exit(cli())
  File "/home/ubuntu/anaconda3/envs/py36/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/ubuntu/anaconda3/envs/py36/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/ubuntu/anaconda3/envs/py36/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/ubuntu/anaconda3/envs/py36/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/ubuntu/anaconda3/envs/py36/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/ubuntu/anaconda3/envs/py36/lib/python3.6/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/ubuntu/anaconda3/envs/py36/lib/python3.6/site-packages/kraken/ketos.py", line 717, in line_generator
    from kraken import linegen
  File "/home/ubuntu/anaconda3/envs/py36/lib/python3.6/site-packages/kraken/linegen.py", line 63, in <module>
    cairo = ctypes.CDLL(c_lib)
  File "/home/ubuntu/anaconda3/envs/py36/lib/python3.6/ctypes/__init__.py", line 348, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /home/ubuntu/anaconda3/envs/py36/lib/cairo: cannot read file data: Is a directory
(py36) ubuntu@tesseract-ocr:~/kraken/tests/resources$
```

**Comment by mittagessen** [comment]
* Shreeshrii :: 2020-02-12 12:47 Wed:
> ```
> (py36) ubuntu@tesseract-ocr:~$ cd  kraken/tests/resources
> (py36) ubuntu@tesseract-ocr:~/kraken/tests/resources$ ketos linegen -ur NFC -u NFD -n 15  --disable-degradation   -f Siddhanta test.txt
> Traceback (most recent call last):
>   File "/home/ubuntu/anaconda3/envs/py36/bin/ketos", line 8, in <module>
>     sys.exit(cli())
>   File "/home/ubuntu/anaconda3/envs/py36/lib/python3.6/site-packages/click/core.py", line 764, in __call__
>     return self.main(*args, **kwargs)
>   File "/home/ubuntu/anaconda3/envs/py36/lib/python3.6/site-packages/click/core.py", line 717, in main
>     rv = self.invoke(ctx)
>   File "/home/ubuntu/anaconda3/envs/py36/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
>     return _process_result(sub_ctx.command.invoke(sub_ctx))
>   File "/home/ubuntu/anaconda3/envs/py36/lib/python3.6/site-packages/click/core.py", line 956, in invoke
>     return ctx.invoke(self.callback, **ctx.params)
>   File "/home/ubuntu/anaconda3/envs/py36/lib/python3.6/site-packages/click/core.py", line 555, in invoke
>     return callback(*args, **kwargs)
>   File "/home/ubuntu/anaconda3/envs/py36/lib/python3.6/site-packages/click/decorators.py", line 17, in new_func
>     return f(get_current_context(), *args, **kwargs)
>   File "/home/ubuntu/anaconda3/envs/py36/lib/python3.6/site-packages/kraken/ketos.py", line 717, in line_generator
>     from kraken import linegen
>   File "/home/ubuntu/anaconda3/envs/py36/lib/python3.6/site-packages/kraken/linegen.py", line 63, in <module>
>     cairo = ctypes.CDLL(c_lib)
>   File "/home/ubuntu/anaconda3/envs/py36/lib/python3.6/ctypes/__init__.py", line 348, in __init__
>     self._handle = _dlopen(self._name, mode)
> OSError: /home/ubuntu/anaconda3/envs/py36/lib/cairo: cannot read file data: Is a directory
> (py36) ubuntu@tesseract-ocr:~/kraken/tests/resources$
> ```

Have you installed cairo from anaconda? There's obviously going
something wrong with resolving the dynamic library paths. I'm not 100%
sure but either deleting that directory (if it is empty) or installing
cairo from conda-forge should solve this error.

**Comment by Shreeshrii** [comment]
@mittagessen  Thanks so much.  deleting that directory worked.

I am able to run ketos train now.
