### ISSUE TITLE
ketos transcribe TypeError argument must be a string, a bytes-like object or a number, not 'tuple'

### ISSUE THREAD

**Issue by PeterVoskuilen** [mittagessen/kraken#216]
kraken, version 3.0.0.0b7.dev10

Hi there, I'm trying to transcribe and use prefill. However an error is thrown.

The command i use:
`ketos transcribe --prefill /srv/data/models/en_best.mlmodel -o output.html 0050.png`

The error i have:
`Loading ANN

Traceback (most recent call last):
  File "/usr/local/bin/ketos", line 10, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/kraken/ketos.py", line 754, in transcription
    ti.add_page(im, res, records=preds)
  File "/usr/local/lib/python3.6/dist-packages/kraken/transcribe.py", line 74, in add_page
    'left': 100*int(bbox[0]) / im.size[0],
TypeError: int() argument must be a string, a bytes-like object or a number, not 'tuple'`

Do i enter a wrong command or is there a bug in the code?

thanks.

**Comment by mittagessen** [comment]
The auto-taggification of untagged segmentations in the recognizer broke it. It's not a very often used code path with the new segmenter and all and is not included in the tests so it didn't crop up earlier.
