### ISSUE TITLE
kraken.lib.exceptions.KrakenEncodeException: No prefix matches for input 

### ISSUE THREAD

**Issue by Shreeshrii** [mittagessen/kraken#222]
While training for Grantha script, kraken is crashing with the following error:

```
[64.2956] Taking 345 lines/files from training set for evaluation 
[64.2958] Loading existing model from linesnew_3.mlmodel  
[65.1757] layer		type	params 
[66.0819] 0		conv	kernel 4 x 2 filters 32 stride (4, 2) activation r 
[66.3108] 1		groupnorm	groups 32 
[66.3116] 2		conv	kernel 4 x 2 filters 64 stride (1, 1) activation r 
[66.3119] 3		groupnorm	groups 32 
[66.3121] 4		maxpool	kernel 4 x 2 stride 4 x 2 
[66.3135] 5		conv	kernel 3 x 3 filters 128 stride (1, 1) activation r 
[66.3138] 6		groupnorm	groups 32 
[66.3140] 7		maxpool	kernel 1 x 2 stride 1 x 2 
[66.3141] 8		reshape from 1 1 x -1 to 1/3 
[66.5865] 9		rnn	direction b transposed False summarize False out 256 legacy None 
[66.5868] 10		dropout	probability 0.5 dims 1 
[66.6092] 11		rnn	direction b transposed False summarize False out 256 legacy None 
[66.6094] 12		dropout	probability 0.5 dims 1 
[66.6326] 13		rnn	direction b transposed False summarize False out 256 legacy None 
[66.6329] 14		dropout	probability 0.5 dims 1 
[66.6343] 15		linear	augmented False out 132 
[71.7357] Setting multiprocessing tensor sharing strategy to file_system 
[71.7984] Adding line {'image': '/home/ubuntu/tess5training-grantha/gt/eval/tam.Noto_Serif_Grantha.0000746.exp0.tif'} to training set 

...

[695.7563] Adding line {'image': '/home/ubuntu/tess5training-grantha/gt/line-scannedimages/grantha2_page_0001_24.png'} to validation set 
[695.7874] Training set 3052 lines, validation set 341 lines, alphabet 130 symbols 
[695.7876] alphabet mismatch: chars in training set only: {'~', '`', '௰', '+', 'ঀ', '{', '"', '?', '_', '<', '!', '>', '—', '𑌌', ']', '%', '‡', '['} (not included in accuracy test during training) 
[695.7877] alphabet mismatch: chars in validation set only: {'}', '௲'} (not trained) 
[695.7877] grapheme	count 
[695.7879] SPACE	19687 
[695.8134] GRANTHA SIGN VIRAMA	14073 
[695.8135] GRANTHA VOWEL SIGN AA	6024 
[695.8136] 	𑌰	5625 
[695.8136] 	𑌤	5327 
[695.8137] 	𑌨	4417 
[695.8138] GRANTHA VOWEL SIGN I	4334 
[695.8138] 	𑌮	3673 
[695.8139] 	𑌵	3667 
[695.8140] 	𑌯	3526 
[695.8140] 	𑌕	3448 
[695.8141] GRANTHA VOWEL SIGN U	3000 
[695.8141] 	𑌪	2716 
[695.8142] GRANTHA VOWEL SIGN EE	2506 
[695.8143] 	𑌸	2354 
[695.8143] 	𑌦	1912 
[695.8144] 	𑌲	1705 
[695.8145] GRANTHA SIGN ANUSVARA	1647 
[695.8145] GRANTHA VOWEL SIGN OO	1585 
[695.8146] 	𑌚	1557 
[695.8147] 	𑌣	1531 
[695.8147] GRANTHA SIGN VISARGA	1486 
[695.8148] 	𑌶	1280 
[695.8149] 	𑌷	1229 
[695.8149] GRANTHA VOWEL SIGN II	1227 
[695.8150] 	.	1193 
[695.8150] 	𑌜	1180 
[695.8151] 	𑌟	1146 
[695.8152] 	𑌗	1074 
[695.8152] 	𑌹	1068 
[695.8153] 	𑌭	1027 
[695.8154] GRANTHA VOWEL SIGN AI	991 
[695.8154] 	𑌧	960 
[695.8155] 	𑌅	956 
[695.8156] 	।	917 
[695.8156] 	-	759 
[695.8157] GRANTHA VOWEL SIGN UU	737 
[695.8157] 	॥	720 
[695.8158] GRANTHA VOWEL SIGN VOCALIC R	693 
[695.8159] 	𑌥	650 
[695.8159] 	𑌳	599 
[695.8160] 	𑌬	597 
[695.8161] 	𑌞	565 
[695.8161] 	𑌙	496 
[695.8162] 	௧	433 
[695.8162] 	𑌇	418 
[695.8163] 	𑌡	379 
[695.8164] 	𑌏	373 
[695.8164] 	𑌉	357 
[695.8165] 	𑌖	355 
[695.8166] 	𑌛	316 
[695.8166] 	௨	309 
[695.8167] 	𑌆	304 
[695.8168] 	௦	291 
[695.8168] GRANTHA AU LENGTH MARK	287 
[695.8169] 	𑌠	285 
[695.8170] GRANTHA SIGN NUKTA	275 
[695.8170] 	,	271 
[695.8171] 	௩	263 
[695.8172] 	𑌽	240 
[695.8172] 	𑌘	234 
[695.8173] 	௮	221 
[695.8173] 	𑌫	217 
[695.8174] 	)	215 
[695.8175] 	௪	210 
[695.8175] 	𑌢	205 
[695.8176] 	௬	177 
[695.8177] 	௫	176 
[695.8177] 	𑍐	174 
[695.8178] 	(	172 
[695.8179] 	௯	164 
[695.8179] 	𑌓	155 
[695.8180] 	௭	155 
[695.8180] 	:	153 
[695.8181] GRANTHA VOWEL SIGN AU	136 
[695.8182] VEDIC TONE CANDRA ABOVE	136 
[695.8182] GRANTHA SIGN COMBINING ANUSVARA ABOVE	108 
[695.8183] 	𑌝	108 
[695.8184] 	/	106 
[695.8184] 	𑌈	92 
[695.8185] 	;	92 
[695.8186] 	𑌊	88 
[695.8186] 	'	88 
[695.8187] 	=	82 
[695.8187] 	𑌋	75 
[695.8188] GRANTHA VOWEL SIGN VOCALIC RR	68 
[695.8189] GRANTHA VOWEL SIGN VOCALIC L	66 
[695.8189] GRANTHA SIGN CANDRABINDU	58 
[695.8190] 	1	51 
[695.8191] 	𑍠	51 
[695.8191] 	2	46 
[695.8192] 	𑍡	46 
[695.8193] 	𑍟	40 
[695.8193] 	𑌐	39 
[695.8194] 	𑍞	38 
[695.8194] 	𑌔	27 
[695.8195] 	3	25 
[695.8196] 	6	22 
[695.8196] 	5	22 
[695.8197] 	*	22 
[695.8198] 	8	21 
[695.8198] 	4	21 
[695.8199] 	0	18 
[695.8199] 	9	18 
[695.8200] 	¬	18 
[695.8201] 	7	17 
[695.8201] 	^	15 
[695.8202] 	_	13 
[695.8203] 	𑍝	12 
[695.8203] 	𑌌	9 
[695.8204] 	`	6 
[695.8204] 	[	5 
[695.8205] 	]	5 
[695.8206] 	<	4 
[695.8206] 	௰	4 
[695.8207] 	௱	4 
[695.8208] 	"	3 
[695.8208] 	‡	3 
[695.8209] 	†	3 
[695.8209] 	—	3 
[695.8210] 	?	3 
[695.8211] 	~	2 
[695.8211] 	>	2 
[695.8212] 	+	2 
[695.8213] 	§	1 
[695.8213] 	%	1 
[695.8214] 	ঀ	1 
[695.8214] 	#	1 
[695.8215] 	{	1 
[695.8216] 	!	1 

[695.8216] Encoding training set 
[695.8259] Resizing network or given codec to Counter({' ': 19687, '𑍍': 14073, '𑌾': 6024, '𑌰': 5625, '𑌤': 5327, '𑌨': 4417, '𑌿': 4334, '𑌮': 3673, '𑌵': 3667, '𑌯': 3526, '𑌕': 3448, '𑍁': 3000, '𑌪': 2716, '𑍇': 2506, '𑌸': 2354, '𑌦': 1912, '𑌲': 1705, '𑌂': 1647, '𑍋': 1585, '𑌚': 1557, '𑌣': 1531, '𑌃': 1486, '𑌶': 1280, '𑌷': 1229, '𑍀': 1227, '.': 1193, '𑌜': 1180, '𑌟': 1146, '𑌗': 1074, '𑌹': 1068, '𑌭': 1027, '𑍈': 991, '𑌧': 960, '𑌅': 956, '।': 917, '-': 759, '𑍂': 737, '॥': 720, '𑍃': 693, '𑌥': 650, '𑌳': 599, '𑌬': 597, '𑌞': 565, '𑌙': 496, '௧': 433, '𑌇': 418, '𑌡': 379, '𑌏': 373, '𑌉': 357, '𑌖': 355, '𑌛': 316, '௨': 309, '𑌆': 304, '௦': 291, '𑍗': 287, '𑌠': 285, '𑌼': 275, ',': 271, '௩': 263, '𑌽': 240, '𑌘': 234, '௮': 221, '𑌫': 217, ')': 215, '௪': 210, '𑌢': 205, '௬': 177, '௫': 176, '𑍐': 174, '(': 172, '௯': 164, '𑌓': 155, '௭': 155, ':': 153, '𑍌': 136, '᳴': 136, '𑌀': 108, '𑌝': 108, '/': 106, '𑌈': 92, ';': 92, '𑌊': 88, "'": 88, '=': 82, '𑌋': 75, '𑍄': 68, '𑍢': 66, '𑌁': 58, '1': 51, '𑍠': 51, '2': 46, '𑍡': 46, '𑍟': 40, '𑌐': 39, '𑍞': 38, '𑌔': 27, '3': 25, '6': 22, '5': 22, '*': 22, '8': 21, '4': 21, '0': 18, '9': 18, '¬': 18, '7': 17, '^': 15, '_': 13, '𑍝': 12, '𑌌': 9, '`': 6, '[': 5, ']': 5, '<': 4, '௰': 4, '௱': 4, '"': 3, '‡': 3, '†': 3, '—': 3, '?': 3, '~': 2, '>': 2, '+': 2, '§': 1, '%': 1, 'ঀ': 1, '#': 1, '{': 1, '!': 1}) code sequences 
[696.3849] Deleting 2 output classes from network (110 retained) 
[696.9341] Resizing output layer to 131 
[697.7536] Constructing Adam optimizer (lr: 0.001, momentum: 0.9) 
[697.7563] Set OpenMP threads to 1 
[697.7602] Moving model to device cpu 
[697.8046] Starting up training... 
[26916.9780] Starting evaluation run 
[27421.9402] Rescaling early stopping loss to inf 
[27421.9407] Resetting early stopping counter 
[27421.9408] Saving to grantha_1 
[52990.9328] Starting evaluation run 
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/kraken/bin/ketos", line 8, in <module>
    sys.exit(cli())
  File "/home/ubuntu/.local/lib/python3.6/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/ubuntu/.local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/kraken/ketos.py", line 439, in train
    trainer.run(_print_eval, _draw_progressbar)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/kraken/lib/train.py", line 425, in run
    eval_res = self.evaluator(self.model, self.val_set, self.device)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/kraken/lib/train.py", line 306, in recognition_evaluator_fn
    chars, error = compute_error(rec, val_loader)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/kraken/lib/dataset.py", line 278, in compute_error
    preds = model.predict_string(batch['image'], batch['seq_lens'])
  File "/home/ubuntu/.local/lib/python3.6/site-packages/kraken/lib/models.py", line 121, in predict_string
    dec_strs.append(''.join(x[0] for x in self.codec.decode(locs)))
  File "/home/ubuntu/.local/lib/python3.6/site-packages/kraken/lib/codec.py", line 118, in decode
    splits = self._greedy_split(uni_labels, self.l2c_regex)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/kraken/lib/codec.py", line 151, in _greedy_split
    raise KrakenEncodeException('No prefix matches for input after {}'.format(idx))
kraken.lib.exceptions.KrakenEncodeException: No prefix matches for input after 41
```

**Comment by Shreeshrii** [comment]
Sample training data is at 
https://github.com/Shreeshrii/images_grantha
