### ISSUE TITLE
Problem with torch version

### ISSUE THREAD

**Issue by Jean-Baptiste-Camps** [mittagessen/kraken#228]
I got a **problem after updating the environnement**, with the following error:

```
Traceback (most recent call last):
  File "/home/jbcamps/anaconda3/envs/kraken/bin/ketos", line 8, in <module>
    sys.exit(cli())
  File "/home/jbcamps/anaconda3/envs/kraken/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/jbcamps/anaconda3/envs/kraken/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/jbcamps/anaconda3/envs/kraken/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/jbcamps/anaconda3/envs/kraken/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/jbcamps/anaconda3/envs/kraken/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/jbcamps/anaconda3/envs/kraken/lib/python3.8/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/jbcamps/anaconda3/envs/kraken/lib/python3.8/site-packages/kraken/ketos.py", line 439, in train
    trainer.run(_print_eval, _draw_progressbar)
  File "/home/jbcamps/anaconda3/envs/kraken/lib/python3.8/site-packages/kraken/lib/train.py", line 410, in run
    o = self.model.nn(input, seq_lens)
  File "/home/jbcamps/anaconda3/envs/kraken/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/jbcamps/anaconda3/envs/kraken/lib/python3.8/site-packages/kraken/lib/layers.py", line 26, in forward
    inputs = module(*inputs)
  File "/home/jbcamps/anaconda3/envs/kraken/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/jbcamps/anaconda3/envs/kraken/lib/python3.8/site-packages/kraken/lib/layers.py", line 373, in forward
    inputs = pack_padded_sequence(inputs, seq_len, batch_first=True, enforce_sorted=False)
  File "/home/jbcamps/anaconda3/envs/kraken/lib/python3.8/site-packages/torch/nn/utils/rnn.py", line 244, in pack_padded_sequence
    _VF._pack_padded_sequence(input, lengths, batch_first)
RuntimeError: 'lengths' argument should be a 1D CPU int64 tensor, but got 1D cuda:0 Long tensor
```

I fixed it by downgrading PyTorch to 1.6.0. Perhaps for the moment adding something like:
`pytorch::pytorch>=1.5.0` to the environment_cuda.yml file.

Should I make a PR ?

**Comment by Jean-Baptiste-Camps** [comment]
PS: My reason for updating was that I wanted to have a Torch compatible with CUDA capability sm_75, so, in this regard, it might be better to solve the actual error and move to PyTorch 1.7.0…

**Comment by mittagessen** [comment]
Uuuugh. Why do they do this?

> I fixed it by downgrading PyTorch to 1.6.0. Perhaps for the moment adding something like:
> `pytorch::pytorch>=1.5.0` to the environment_cuda.yml file.
> 
> Should I make a PR ?

Yes please. I'll take a look later to see if anything else is broken by
1.7.

**Comment by mittagessen** [comment]
I skimmed through the pytorch changelog to see if there are any other breaking changes. They also changed the API of torchvision completely. I'll have to run some tests to verify everything is working correctly, then we can unpin the version again. Hopefully it can be kept backwards compatible as 1.6/1.7 don't work on many HPC clusters.

**Comment by mittagessen** [comment]
The latest commit on master (0d5f6b339d967ee71da7a255546757c438593fc9) is compatible with pytorch 1.7 again.

**Comment by Jean-Baptiste-Camps** [comment]
Great, thanks !
