### ISSUE TITLE
AttributeError: Can't pickle local object 'PolygonGTDataset.__init__. 

### ISSUE THREAD

**Issue by Benedetta-Salvati** [mittagessen/kraken#229]
I am working with a mac (10.15.6). I installed Kraken with Conda. I got my data from Transkribus and I use pageXML documents to train a model and I got the error _infra_. 
```
ketos train -t train.txt -e val.txt -f page 
[0.0050] Invalid entry "" in train.txt 
Building training set  [####################################]  210/210          
Building validation set  [####################################]  68/68          [398.5864] alphabet mismatch: chars in training set only: {'V', 'G', 'ƥ', 'ꝑ', '/', 'N', '6', '2', 'ū', 'ꝯ', "'", 'ā', 'I'} (not included in accuracy test during training) 
WARNING:kraken.lib.train:alphabet mismatch: chars in training set only: {'V', 'G', 'ƥ', 'ꝑ', '/', 'N', '6', '2', 'ū', 'ꝯ', "'", 'ā', 'I'} (not included in accuracy test during training)
[398.5867] alphabet mismatch: chars in validation set only: {'9', '0', 'O', 'B'} (not trained) 
WARNING:kraken.lib.train:alphabet mismatch: chars in validation set only: {'9', '0', 'O', 'B'} (not trained)
Initializing model ✓
Traceback (most recent call last):
  File "/opt/anaconda3/envs/kraken/bin/ketos", line 8, in <module>
    sys.exit(cli())
  File "/opt/anaconda3/envs/kraken/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/opt/anaconda3/envs/kraken/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/opt/anaconda3/envs/kraken/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/anaconda3/envs/kraken/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/anaconda3/envs/kraken/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/opt/anaconda3/envs/kraken/lib/python3.8/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/opt/anaconda3/envs/kraken/lib/python3.8/site-packages/kraken/ketos.py", line 404, in train
    trainer = KrakenTrainer.recognition_train_gen(hyper_params,
  File "/opt/anaconda3/envs/kraken/lib/python3.8/site-packages/kraken/lib/train.py", line 690, in recognition_train_gen
    train_loader = InfiniteDataLoader(gt_set, batch_size=hyper_params['batch_size'],
  File "/opt/anaconda3/envs/kraken/lib/python3.8/site-packages/kraken/lib/dataset.py", line 374, in __init__
    self.dataset_iter = super().__iter__()
  File "/opt/anaconda3/envs/kraken/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 352, in __iter__
    return self._get_iterator()
  File "/opt/anaconda3/envs/kraken/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 294, in _get_iterator
    return _MultiProcessingDataLoaderIter(self)
  File "/opt/anaconda3/envs/kraken/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 801, in __init__
    w.start()
  File "/opt/anaconda3/envs/kraken/lib/python3.8/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/opt/anaconda3/envs/kraken/lib/python3.8/multiprocessing/context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "/opt/anaconda3/envs/kraken/lib/python3.8/multiprocessing/context.py", line 284, in _Popen
    return Popen(process_obj)
  File "/opt/anaconda3/envs/kraken/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/opt/anaconda3/envs/kraken/lib/python3.8/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/opt/anaconda3/envs/kraken/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 47, in _launch
    reduction.dump(process_obj, fp)
  File "/opt/anaconda3/envs/kraken/lib/python3.8/multiprocessing/reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
AttributeError: Can't pickle local object 'PolygonGTDataset.__init__.<locals>.<lambda>'
(kraken) bsalvati@LETTRES36003 testmodel % 
```

**Comment by mittagessen** [comment]
* Benedetta-Salvati :: 2020-12-21 16:00 Mon:
> I am working with a mac (10.15.6). I installed Kraken with Conda. I
> got my data from Transkribus and I use pageXML documents to train a
> model and I got the error _infra_. 

Pytorch's multiprocessing module seems to function differently under Mac
OS X than Linux. You can disable multiprocessing with `--threads 1` but
loading data and training in the same process incurs a performance
penalty (which shouldn't be that high in your case as the lines are
preloaded so there isn't really much happening in the loader during
training).

I don't have access to a Mac OS machine but will see if I can find a
better solution after christmas.

**Comment by kba** [comment]
> I don't have access to a Mac OS machine

Me neither but a little tip: CircleCI allows processing on MacOSX and logging in via SSH into a failed run. I've used that in the past to debug OSX issues without a Mac.

**Comment by mittagessen** [comment]
In the course of parallelizing dataset loading the datasets are pickleable now. This should resolve this issue.
