### ISSUE TITLE
MemoryError while training with last release (3.0b25)

### ISSUE THREAD

**Issue by alix-tz** [mittagessen/kraken#253]
Hello, 

I'm using the last version of Kraken on a rather huge dataset (641 pages from the Répertoires de Notaire - between 200 and 300 lines/document). I got the following error, which I think can be linked to the issue #242

I ran this command: `ketos train -o mega_random_set_kraken -f page -t allxmls.xmllist --device cuda:0 --augment --threads 64 -u NFD -s '[1,120,0,1 Cr3,13,32 Do0.1,2 Mp2,2 Cr3,13,32 Do0.1,2 Mp2,2 Cr3,9,64 Do0.1,2 Mp2,2 Cr3,9,64 Do0.1,2 S1(1x0)1,3 Lbx200 Do0.1,2 Lbx200 Do.1,2 Lbx200 Do]' -r 0.0001 --preload`

```
Building training set  [#########################-----------]  68335/95912  01:20:06multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/ROCQ/almanach/achague/anaconda3/envs/kraken_v3_0b25/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/home/ROCQ/almanach/achague/anaconda3/envs/kraken_v3_0b25/lib/python3.8/multiprocessing/pool.py", line 48, in mapstar
    return list(map(*args))
  File "/home/ROCQ/almanach/achague/anaconda3/envs/kraken_v3_0b25/lib/python3.8/site-packages/kraken/lib/train.py", line 47, in _star_fun
    return fun(**kwargs)
  File "/home/ROCQ/almanach/achague/anaconda3/envs/kraken_v3_0b25/lib/python3.8/site-packages/kraken/lib/dataset.py", line 471, in parse
    im, _ = next(extract_polygons(im, {'type': 'baselines', 'lines': [{'baseline': baseline, 'boundary': boundary}]}))
  File "/home/ROCQ/almanach/achague/anaconda3/envs/kraken_v3_0b25/lib/python3.8/site-packages/kraken/lib/segmentation.py", line 859, in extract_polygons
    im = np.array(im)
  File "/home/ROCQ/almanach/achague/anaconda3/envs/kraken_v3_0b25/lib/python3.8/site-packages/PIL/Image.py", line 692, in __array_interface__
    new["data"] = self.tobytes()
  File "/home/ROCQ/almanach/achague/anaconda3/envs/kraken_v3_0b25/lib/python3.8/site-packages/PIL/Image.py", line 734, in tobytes
    self.load()
  File "/home/ROCQ/almanach/achague/anaconda3/envs/kraken_v3_0b25/lib/python3.8/site-packages/PIL/ImageFile.py", line 211, in load
    self.load_prepare()
  File "/home/ROCQ/almanach/achague/anaconda3/envs/kraken_v3_0b25/lib/python3.8/site-packages/PIL/ImageFile.py", line 281, in load_prepare
    self.im = Image.core.new(self.mode, self.size)
MemoryError
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ROCQ/almanach/achague/anaconda3/envs/kraken_v3_0b25/bin/ketos", line 8, in <module>
    sys.exit(cli())
  File "/home/ROCQ/almanach/achague/anaconda3/envs/kraken_v3_0b25/lib/python3.8/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/home/ROCQ/almanach/achague/anaconda3/envs/kraken_v3_0b25/lib/python3.8/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/home/ROCQ/almanach/achague/anaconda3/envs/kraken_v3_0b25/lib/python3.8/site-packages/click/core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/ROCQ/almanach/achague/anaconda3/envs/kraken_v3_0b25/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/ROCQ/almanach/achague/anaconda3/envs/kraken_v3_0b25/lib/python3.8/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/home/ROCQ/almanach/achague/anaconda3/envs/kraken_v3_0b25/lib/python3.8/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/ROCQ/almanach/achague/anaconda3/envs/kraken_v3_0b25/lib/python3.8/site-packages/kraken/ketos.py", line 427, in train
    trainer = KrakenTrainer.recognition_train_gen(hyper_params,
  File "/home/ROCQ/almanach/achague/anaconda3/envs/kraken_v3_0b25/lib/python3.8/site-packages/kraken/lib/train.py", line 635, in recognition_train_gen
    for im in pool.imap_unordered(partial(_star_fun, gt_set.parse), training_data, 5):
  File "/home/ROCQ/almanach/achague/anaconda3/envs/kraken_v3_0b25/lib/python3.8/multiprocessing/pool.py", line 448, in <genexpr>
    return (item for chunk in result for item in chunk)
  File "/home/ROCQ/almanach/achague/anaconda3/envs/kraken_v3_0b25/lib/python3.8/multiprocessing/pool.py", line 868, in next
    raise value
MemoryError
```

Did I just used too many files for the training set or is there something that can be done to fix this issue? Is it because of the preload option?

**Comment by alix-tz** [comment]
I edited the initial message with the command I passed to Kraken, which included `--preload`

**Comment by alix-tz** [comment]
I tried the same command without `--preload` and it worked, so I'm closing this issue!
