### ISSUE TITLE
Error about GeometryCollection

### ISSUE THREAD

**Issue by Heresta** [mittagessen/kraken#254]
Hi,

I have an issue when I tried to use kraken with a segmentation and a HTR model.

As you can see in this screenshot, an error is raised.
![image](https://user-images.githubusercontent.com/74970052/120657495-d6004080-c484-11eb-95fb-1b5ead7eeb23.png)

I am using a environment pip and Kraken v. 3.0.0.0b25.dev6

Thanks in advance for your help

**Comment by PonteIneptique** [comment]
Traceback with --abby, --page and --alto:

```
Traceback (most recent call last):
  File "/anaconda3/envs/kraken/bin/kraken", line 8, in <module>
    sys.exit(cli())
  File "/anaconda3/envs/kraken/lib/python3.8/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/anaconda3/envs/kraken/lib/python3.8/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/anaconda3/envs/kraken/lib/python3.8/site-packages/click/core.py", line 1700, in invoke
    return _process_result(rv)
  File "/anaconda3/envs/kraken/lib/python3.8/site-packages/click/core.py", line 1637, in _process_result
    value = ctx.invoke(self._result_callback, value, **ctx.params)
  File "/anaconda3/envs/kraken/lib/python3.8/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/anaconda3/envs/kraken/lib/python3.8/site-packages/kraken/kraken.py", line 370, in process_pipeline
    task(input=input, output=output)
  File "/anaconda3/envs/kraken/lib/python3.8/site-packages/kraken/kraken.py", line 237, in recognizer
    fp.write(serialization.serialize(preds, ctx.meta['base_image'],
  File "/anaconda3/envs/kraken/lib/python3.8/site-packages/kraken/serialization.py", line 198, in serialize
    coords = np.array(pols.convex_hull.exterior.coords, dtype=np.uint).tolist()
AttributeError: 'GeometryCollection' object has no attribute 'exterior'
```

**Comment by mittagessen** [comment]
Thanks. Could you give me the image and model that produced this crash?
It's a shapely corner case and those are basically undebuggable without
sample data.

**Comment by PonteIneptique** [comment]
[simon.zip](https://github.com/mittagessen/kraken/files/6647501/simon.zip)

Command run:

```
kraken -i Cat_Courbet_1882-1_typo_0001.jpg out.xml --alto --raise-on-error  segment -i Juliette.mlmodel ocr -m model_best_100.mlmodel
```

**Comment by mittagessen** [comment]
Thanks. The problem was caused by a point-shaped character cut which broke the Polygon/LineString buffer logic that buffers out zero area cuts.
