### ISSUE TITLE
ketos test is broken

### ISSUE THREAD

**Issue by dstoekl** [mittagessen/kraken#255]
same list and model work in previous release. now it gives the following error:

ketos test -m x.mlmodel -e y.xmllist  -f xml                                                                  
Loading model ../models/transcription/x.mlmodel        ✓
Evaluating ../models/transcription/x.mlmodel
Traceback (most recent call last):
  File "/pbs/home/d/dstoekl/anaconda/envs/kraken7/bin/ketos", line 10, in <module>
    sys.exit(cli())
  File "/pbs/home/d/dstoekl/anaconda/envs/kraken7/lib/python3.8/site-packages/click/core.py", line 1134, in __call__
    return self.main(*args, **kwargs)
  File "/pbs/home/d/dstoekl/anaconda/envs/kraken7/lib/python3.8/site-packages/click/core.py", line 1059, in main
    rv = self.invoke(ctx)
  File "/pbs/home/d/dstoekl/anaconda/envs/kraken7/lib/python3.8/site-packages/click/core.py", line 1665, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/pbs/home/d/dstoekl/anaconda/envs/kraken7/lib/python3.8/site-packages/click/core.py", line 1401, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/pbs/home/d/dstoekl/anaconda/envs/kraken7/lib/python3.8/site-packages/click/core.py", line 767, in invoke
    return __callback(*args, **kwargs)
  File "/pbs/home/d/dstoekl/anaconda/envs/kraken7/lib/python3.8/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/sps/humanum/eScriptorium/dstoekl/mittagessen/kraken7/kraken/kraken/ketos.py", line 583, in test
    ds.add(**line)
  File "/sps/humanum/eScriptorium/dstoekl/mittagessen/kraken7/kraken/kraken/lib/dataset.py", line 438, in add
    kwargs = self.parse(image, text, baseline, boundary, *args, **kwargs)
NameError: name 'image' is not defined

**Comment by mittagessen** [comment]
This regression has already been fixed earlier last week. Please update.
