### ISSUE TITLE
Strange IOError in current version

### ISSUE THREAD

**Issue by lunactic** [mittagessen/kraken#26]
I'm trying to run the OCR on e test image (http://www.anycount.com/WordCountBlog/wp-content/uploads/2009/07/test-english-shht.jpg) on the current version.

When I run the command (after renaming the image):

```
kraken -i input1.jpg ocr.txt binarize segment ocr --model ~/.config/kraken/en-default.pronn 
```` 

I get this strange IOError:

```
Traceback (most recent call last):
  File "/usr/bin/kraken", line 10, in <module>
    sys.exit(cli())
  File "/usr/lib/python2.7/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 1087, in invoke
    return _process_result(rv)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 1025, in _process_result
    **ctx.params)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/kraken/kraken.py", line 144, in process_pipeline
    task(base_image=base_image, input=input, output=output)
  File "/usr/lib/python2.7/site-packages/kraken/kraken.py", line 61, in binarizer
    low, high)
  File "/usr/lib/python2.7/site-packages/kraken/binarization.py", line 64, in nlbin
    raw = pil2array(im)
  File "/usr/lib/python2.7/site-packages/kraken/lib/util.py", line 22, in pil2array
    a = np.fromstring(im.tobytes(), 'B')
  File "/usr/lib/python2.7/site-packages/PIL/Image.py", line 673, in tobytes
    self.load()
  File "/usr/lib/python2.7/site-packages/PIL/ImageFile.py", line 222, in load
    "(%d bytes not processed)" % len(b))
```

From StackOverflow I saw a possible solution but didn't try it out myself yet.
https://stackoverflow.com/questions/12984426/python-pil-ioerror-image-file-truncated-with-big-images
(not the accepted solution but the second one)

Do you have any ideas what might cause this?

**Comment by lunactic** [comment]
Update:

Seems to be an issue with wget not downloading the whole image or something. If I download the same image with curl it magically works...

feel free to close the issue
