### ISSUE TITLE
ketos test: NameError: name 'image' is not defined in version 3.0b25

### ISSUE THREAD

**Issue by rohanchn** [mittagessen/kraken#260]
model evaluation command ( `ketos test -d cuda:0 -m 3n_best.mlmodel -e test.txt gt/*.png` ) is throwing the following the error in version 3.0b25: 

`Traceback (most recent call last):
  File "/home/rohan/codes/kraken/venv/bin/ketos", line 8, in <module>
    sys.exit(cli())
  File "/home/rohan/codes/kraken/venv/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/rohan/codes/kraken/venv/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/rohan/codes/kraken/venv/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/rohan/codes/kraken/venv/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/rohan/codes/kraken/venv/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/rohan/codes/kraken/venv/lib/python3.8/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/rohan/codes/kraken/venv/lib/python3.8/site-packages/kraken/ketos.py", line 583, in test
    ds.add(**line)
  File "/home/rohan/codes/kraken/venv/lib/python3.8/site-packages/kraken/lib/dataset.py", line 630, in add
    kwargs = self.parse(image, *args, **kwargs)
NameError: name 'image' is not defined`

The same command is working fine in version 3.0b24. 

Could you please clarify what's wrong?

**Comment by mittagessen** [comment]
That's a regression that was introduced when I split the dataset
construction into 2 functions to allow for parallelized loading. It has
been fixed for quite a while now in master but I haven't tagged a new
release which includes the patch, yet.

**Comment by rohanchn** [comment]
Thank you for your help. 

I have another question not related to this issue. Allow me to ask it here.
  
How many lines of gt do I need for a reliable text recognition model while training with data exported from eScriptorium? 
I was getting reliable results (99%+) with around 800-900 lines when I was training with data from kraken's default training environment. Training for subsequent books required far fewer lines. 
However, I haven't moved past 90% with data exported from eScriptorium even with 1500+ lines. I am training a new model from scratch as you suggested previously in #252.  
Could you please explain where I am erring ?

**Comment by dstoekl** [comment]
do you use --resize both or --resize add?

**Comment by rohanchn** [comment]
I --resize add

**Comment by rohanchn** [comment]
Accuracy has immsenly improved in my new eScriptorium install. I guess, something was wrong either with my old install or the way I was exporting data from it. It seems to working fine for now. 
I am closign this issue. 
Thank you for hard work.
