### ISSUE TITLE
ketos train - Alto Parsing - Extract polygon failure

### ISSUE THREAD

**Issue by PonteIneptique** [mittagessen/kraken#272]
A dataset I am training on can't be parsed, it throws an error as it parses one of the element (unfortunately, now way to know which currently):
```python-tb
Building training set  [#######-----------------------------]  4455/20268  00:25:40
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "anaconda3/envs/kraken/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "anaconda3/envs/kraken/lib/python3.8/multiprocessing/pool.py", line 48, in mapstar
    return list(map(*args))
  File "anaconda3/envs/kraken/lib/python3.8/site-packages/kraken/lib/train.py", line 47, in _star_fun
    return fun(**kwargs)
  File "anaconda3/envs/kraken/lib/python3.8/site-packages/kraken/lib/dataset.py", line 489, in parse
    im, _ = next(extract_polygons(im, {'type': 'baselines', 'lines': [{'baseline': baseline, 'boundary': boundary}]}))
  File "anaconda3/envs/kraken/lib/python3.8/site-packages/kraken/lib/segmentation.py", line 901, in extract_polygons
    if (pl < 0).any() or (pl.max(axis=0)[::-1] >= im.shape[:2]).any():
ValueError: operands could not be broadcast together with shapes (2,) (0,) ****
```

**Comment by PonteIneptique** [comment]
Ok, I added an except in my local install and found out this file is messing stuff up : 

- https://github.com/Heresta/OCR17plus/blob/11f57a5cddacae7ed42326f0070fbd4123b1b1ba/Data/Scudery1641_Ibrahim_cb31341849n_corrected/png/Scudery1641_Ibrahim_cb31341849n_corrected_0092.png
- https://github.com/Heresta/OCR17plus/blob/11f57a5cddacae7ed42326f0070fbd4123b1b1ba/Data/Scudery1641_Ibrahim_cb31341849n_corrected/alto4eScriptorium/Scudery1641_Ibrahim_cb31341849n_corrected_0092.xml

**Comment by mittagessen** [comment]
Seems like an invalid line shape. It shouldn't crash but print a warning instead.

**Comment by mittagessen** [comment]
Are you sure it is this file? Because it works perfectly well for me.

**Comment by PonteIneptique** [comment]
Actually, yes, it is, but as I look at the log of training on the **same** dataset, while not changing anything about input files, this actually varied with 0046 and 0063 as well.

PIP Freeze:
```
albumentations==1.0.0
attr==0.3.1
attrs @ file:///tmp/build/80754af9/attrs_1620827162558/work
brotlipy==0.7.0
certifi==2021.5.30
cffi @ file:///tmp/build/80754af9/cffi_1613246945912/work
chardet @ file:///tmp/build/80754af9/chardet_1607706746162/work
chocomufin==0.0.4
click @ file:///tmp/build/80754af9/click_1621604852318/work
cloudpickle @ file:///tmp/build/80754af9/cloudpickle_1598884132938/work
coremltools==4.1
cryptography @ file:///tmp/build/80754af9/cryptography_1616769286105/work
cycler==0.10.0
cytoolz==0.11.0
dask @ file:///tmp/build/80754af9/dask-core_1623085854073/work
dataclasses==0.6
decorator @ file:///tmp/build/80754af9/decorator_1621259047763/work
fsspec @ file:///tmp/build/80754af9/fsspec_1617959894824/work
future==0.18.2
idna @ file:///home/linux1/recipes/ci/idna_1610986105248/work
imagecodecs @ file:///tmp/build/80754af9/imagecodecs_1623222745143/work
imageio @ file:///tmp/build/80754af9/imageio_1617700267927/work
importlib-metadata @ file:///tmp/build/80754af9/importlib-metadata_1617874469820/work
Jinja2 @ file:///tmp/build/80754af9/jinja2_1621238361758/work
jsonschema @ file:///tmp/build/80754af9/jsonschema_1602607155483/work
kiwisolver @ file:///tmp/build/80754af9/kiwisolver_1612282420641/work
kraken @ file:///home/apinche/kraken
locket==0.2.1
lxml @ file:///tmp/build/80754af9/lxml_1616443220220/work
MarkupSafe @ file:///tmp/build/80754af9/markupsafe_1621528148836/work
matplotlib @ file:///tmp/build/80754af9/matplotlib-suite_1613407855456/work
mkl-fft==1.3.0
mkl-random @ file:///tmp/build/80754af9/mkl_random_1618853849286/work
mkl-service==2.3.0
mpmath==1.2.1
mufidecode==0.1.0
networkx @ file:///tmp/build/80754af9/networkx_1598376031484/work
numpy==1.19.5
olefile==0.46
opencv-python-headless==4.5.2.54
packaging==20.9
partd @ file:///tmp/build/80754af9/partd_1618000087440/work
Pillow @ file:///tmp/build/80754af9/pillow_1617383569452/work
pkgconfig==1.5.4
protobuf==3.14.0
pycparser @ file:///tmp/build/80754af9/pycparser_1594388511720/work
pyOpenSSL @ file:///tmp/build/80754af9/pyopenssl_1608057966937/work
pyparsing @ file:///home/linux1/recipes/ci/pyparsing_1610983426697/work
pyrsistent @ file:///tmp/build/80754af9/pyrsistent_1600141720057/work
PySocks @ file:///tmp/build/80754af9/pysocks_1605305779399/work
python-bidi==0.4.2
python-dateutil @ file:///home/ktietz/src/ci/python-dateutil_1611928101742/work
pyvips @ file:///home/conda/feedstock_root/build_artifacts/pyvips_1602667903026/work
PyWavelets @ file:///tmp/build/80754af9/pywavelets_1601658317819/work
PyYAML==5.4.1
regex @ file:///tmp/build/80754af9/regex_1617569202463/work
requests @ file:///tmp/build/80754af9/requests_1608241421344/work
scikit-image==0.17.2
scipy @ file:///tmp/build/80754af9/scipy_1618855647378/work
Shapely @ file:///tmp/build/80754af9/shapely_1599817083863/work
six @ file:///tmp/build/80754af9/six_1605205327372/work
sympy==1.8
tabulate==0.8.9
tifffile @ file:///tmp/build/80754af9/tifffile_1619636090847/work
toolz @ file:///home/linux1/recipes/ci/toolz_1610987900194/work
torch==1.7.0
torchvision==0.8.1
tornado @ file:///tmp/build/80754af9/tornado_1606942300299/work
tqdm==4.61.1
typing-extensions @ file:///home/ktietz/src/ci_mi/typing_extensions_1612808209620/work
Unidecode==1.2.0
urllib3 @ file:///tmp/build/80754af9/urllib3_1615837158687/work
zipp @ file:///tmp/build/80754af9/zipp_1615904174917/work
```

(If you have a recommandation to avoid the `@ file`... ;) )
