### ISSUE TITLE
Error running segtrain for kraken, version 3.0.6.dev4

### ISSUE THREAD

**Issue by hlapin** [mittagessen/kraken#273]
Run (in colab on GPU runtime): 
````
!ketos segtrain \
-tl \
-o {out}{proj_name}{trial}_ \
-i {seg_models_path}{seg_model} \
-t {training}{proj_name}.txt \
-e {training}{proj_name}.txt \
--quit early \
-f xml \
-d cuda:0 \
--resize both \
-vr Main \
-vr Margin \
-vr Illustration
````
Data and model load, and then:  

````
Fitting network exactly to training set Adding 3 missing types and removing 1 to network output layer ✓
[5.8486] Setting baseline location to topline from unset model. 
Training line types:
  Correction	2	147
  default	3	2799
  Main	6	1
  Title	7	20
Training region types:
  Margin	4	95
  Main	5	87
  Illustration	8	23
stage 1/∞  [####################################]  89/89          
Traceback (most recent call last):
  File "/usr/local/bin/ketos", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/kraken/ketos.py", line 283, in segtrain
    trainer.run(_print_eval, _draw_progressbar)
  File "/usr/local/lib/python3.7/dist-packages/kraken/lib/train.py", line 469, in run
    self.stopper.update(eval_res['val_metric'])
  File "/usr/local/lib/python3.7/dist-packages/kraken/lib/train.py", line 260, in update
    if np.isclose(1., val_loss):
  File "<__array_function__ internals>", line 6, in isclose
  File "/usr/local/lib/python3.7/dist-packages/numpy/core/numeric.py", line 2249, in isclose
    y = asanyarray(b)
  File "/usr/local/lib/python3.7/dist-packages/numpy/core/_asarray.py", line 138, in asanyarray
    return array(a, dtype, copy=False, order=order, subok=True)
  File "/usr/local/lib/python3.7/dist-packages/torch/tensor.py", line 630, in __array__
    return self.numpy()
TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.
````

**Comment by hlapin** [comment]
Follow up: Went back to version 3.0.2, which did not cause that error

**Comment by mittagessen** [comment]
Sorry for the problem. It is fixed in the latest master. Just a stupid little mistake...
