### ISSUE TITLE
CUDA out of memory: Memory Leak Issue?

### ISSUE THREAD

**Issue by rohanchn** [mittagessen/kraken#277]
I keep running into RuntimeError when I try to train segmentation model using data annotated in eScriptorium. `ketos train` runs without errors.

This always happens in the first iteration. And only when I call `ketos segtrain`

I can assure that I have no other process running on my GPU, and it's mostly free when I check `nvidia-smi.` Plus, the error suggests a lot of memory reserverd by PyTorch, which is the confusing part.

I'm using kraken==3.0.4

Can you please help? 

Here's the full report: 

`Traceback (most recent call last):
  File "/home/rohan/codes/kraken/venv/bin/ketos", line 8, in <module>
    sys.exit(cli())
  File "/home/rohan/codes/kraken/venv/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/rohan/codes/kraken/venv/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/rohan/codes/kraken/venv/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/rohan/codes/kraken/venv/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/rohan/codes/kraken/venv/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/rohan/codes/kraken/venv/lib/python3.8/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/rohan/codes/kraken/venv/lib/python3.8/site-packages/kraken/ketos.py", line 283, in segtrain
    trainer.run(_print_eval, _draw_progressbar)
  File "/home/rohan/codes/kraken/venv/lib/python3.8/site-packages/kraken/lib/train.py", line 452, in run
    loss.backward()
  File "/home/rohan/codes/kraken/venv/lib/python3.8/site-packages/torch/tensor.py", line 221, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/home/rohan/codes/kraken/venv/lib/python3.8/site-packages/torch/autograd/__init__.py", line 130, in backward
    Variable._execution_engine.run_backward(
RuntimeError: CUDA out of memory. Tried to allocate 428.00 MiB (GPU 0; 3.82 GiB total capacity; 1.70 GiB already allocated; 312.06 MiB free; 2.19 GiB reserved in total by PyTorch)`

**Comment by mittagessen** [comment]
You need roughly 6Gb of GPU memory to train a segmentation model
(depends a bit on what exactly you're training for and obviously
fiddling with the VGSL config can increase that). From the error message
I gather that you've only got 2Gb which sadly isn't sufficient.

**Comment by rohanchn** [comment]
Thanks for the quick update. 

My current card is 4GB, but that's not quite what you've mentioned. 

I suppose if I am able to pair two cards, I can get it to work. Right?

**Comment by amitdo** [comment]
Maybe you can use the free tier in one of the big cloud providers for training.

**Comment by rohanchn** [comment]
Thank you for your input, @amitdo

That came to mind too after I closed this issue. I have fewer pages right now, but will need to look elsewhere soon.
