### ISSUE TITLE
Does not install in Python 3.10

### ISSUE THREAD

**Issue by dirkroorda** [mittagessen/kraken#308]
Kraken does not install under macos and Python 3.10.

I tried it in a brand new vanilla installation from python.org.
After installing Python 3.10 I did

```
pip3 install --upgrade pip
```

and then

```
pip3 install kraken
```

A curious thing that happens is this:

```
Collecting kraken
  Downloading kraken-3.0.6-py3-none-any.whl (5.4 MB)
     |████████████████████████████████| 5.4 MB 7.0 MB/s            
Collecting jsonschema
  Downloading jsonschema-4.2.1-py3-none-any.whl (69 kB)
     |████████████████████████████████| 69 kB 8.8 MB/s             
Collecting kraken
  Downloading kraken-3.0.4-py3-none-any.whl (5.4 MB)
     |████████████████████████████████| 5.4 MB 11.7 MB/s            
  Downloading kraken-3.0.2-py3-none-any.whl (5.4 MB)
     |████████████████████████████████| 5.4 MB 11.8 MB/s            
  Downloading kraken-3.0.1-py3-none-any.whl (5.5 MB)
     |████████████████████████████████| 5.5 MB 10.1 MB/s            
  Downloading kraken-2.0.8-py3-none-any.whl (643 kB)
     |████████████████████████████████| 643 kB 11.5 MB/s            
Collecting coremltools
  Downloading coremltools-5.1.0.tar.gz (926 kB)
     |████████████████████████████████| 926 kB 12.9 MB/s            
  Preparing metadata (setup.py) ... done
Collecting kraken
  Downloading kraken-2.0.5-py3-none-any.whl (643 kB)
     |████████████████████████████████| 643 kB 10.4 MB/s            
  Downloading kraken-2.0.4-py3-none-any.whl (643 kB)
     |████████████████████████████████| 643 kB 11.2 MB/s            
  Downloading kraken-2.0.3-py3-none-any.whl (643 kB)
     |████████████████████████████████| 643 kB 12.1 MB/s            
  Downloading kraken-2.0.2-py3-none-any.whl (643 kB)
     |████████████████████████████████| 643 kB 12.1 MB/s            
  Downloading kraken-2.0.1-py2.py3-none-any.whl (642 kB)
     |████████████████████████████████| 642 kB 11.7 MB/s            
  Downloading kraken-2.0.0-py2.py3-none-any.whl (642 kB)
     |████████████████████████████████| 642 kB 11.3 MB/s            
  Downloading kraken-1.0.1-py2.py3-none-any.whl (636 kB)
     |████████████████████████████████| 636 kB 10.7 MB/s            
  Downloading kraken-1.0.0-py2.py3-none-any.whl (636 kB)
     |████████████████████████████████| 636 kB 10.5 MB/s            
  Downloading kraken-0.9.16-py2.py3-none-any.whl (595 kB)
     |████████████████████████████████| 595 kB 12.0 MB/s            
Collecting scipy
  Downloading scipy-1.7.2-cp310-cp310-macosx_10_9_x86_64.whl (33.2 MB)
     |████████████████████████████████| 33.2 MB 11.7 MB/s      
 ```

Pip goes back to kraken 0.9.16! It seems that there is an unmet requirement.

Then later the installation fails with an error while installing clstm, which tries to run swig and fails.

```
Collecting kraken
  Downloading kraken-3.0.6-py3-none-any.whl (5.4 MB)
     |████████████████████████████████| 5.4 MB 7.0 MB/s            
Collecting jsonschema
  Downloading jsonschema-4.2.1-py3-none-any.whl (69 kB)
     |████████████████████████████████| 69 kB 8.8 MB/s             
Collecting kraken
  Downloading kraken-3.0.4-py3-none-any.whl (5.4 MB)
     |████████████████████████████████| 5.4 MB 11.7 MB/s            
  Downloading kraken-3.0.2-py3-none-any.whl (5.4 MB)
     |████████████████████████████████| 5.4 MB 11.8 MB/s            
  Downloading kraken-3.0.1-py3-none-any.whl (5.5 MB)
     |████████████████████████████████| 5.5 MB 10.1 MB/s            
  Downloading kraken-2.0.8-py3-none-any.whl (643 kB)
     |████████████████████████████████| 643 kB 11.5 MB/s            
Collecting coremltools
  Downloading coremltools-5.1.0.tar.gz (926 kB)
     |████████████████████████████████| 926 kB 12.9 MB/s            
  Preparing metadata (setup.py) ... done
Collecting kraken
  Downloading kraken-2.0.5-py3-none-any.whl (643 kB)
     |████████████████████████████████| 643 kB 10.4 MB/s            
  Downloading kraken-2.0.4-py3-none-any.whl (643 kB)
     |████████████████████████████████| 643 kB 11.2 MB/s            
  Downloading kraken-2.0.3-py3-none-any.whl (643 kB)
     |████████████████████████████████| 643 kB 12.1 MB/s            
  Downloading kraken-2.0.2-py3-none-any.whl (643 kB)
     |████████████████████████████████| 643 kB 12.1 MB/s            
  Downloading kraken-2.0.1-py2.py3-none-any.whl (642 kB)
     |████████████████████████████████| 642 kB 11.7 MB/s            
  Downloading kraken-2.0.0-py2.py3-none-any.whl (642 kB)
     |████████████████████████████████| 642 kB 11.3 MB/s            
  Downloading kraken-1.0.1-py2.py3-none-any.whl (636 kB)
     |████████████████████████████████| 636 kB 10.7 MB/s            
  Downloading kraken-1.0.0-py2.py3-none-any.whl (636 kB)
     |████████████████████████████████| 636 kB 10.5 MB/s            
  Downloading kraken-0.9.16-py2.py3-none-any.whl (595 kB)
     |████████████████████████████████| 595 kB 12.0 MB/s            
Collecting scipy
  Downloading scipy-1.7.2-cp310-cp310-macosx_10_9_x86_64.whl (33.2 MB)
     |████████████████████████████████| 33.2 MB 11.7 MB/s      
```

It seems that I needed to install `wheel` before attempting to install `kraken`.

So I removed python 3.10 completely, reinstalled it, upgraded pip and did

```
pip3 install wheel
```

before

```
pip3 install kraken
```

It gives a lot of error messages while trying to install Shapely. It tries versions 1.8.0 to 1.5.10 which all fail with different messages. Most versions errored with this:

```
Collecting shapely
  Downloading Shapely-1.8.0.tar.gz (278 kB)
     |████████████████████████████████| 278 kB 13.2 MB/s            
  Preparing metadata (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /Library/Frameworks/Python.framework/Versions/3.10/bin/python3.10 -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/nb/_qgnfkns75bcn_p_msyjl81m0000gn/T/pip-install-r5n2ridh/shapely_58657eb7ef98443a9067e2c264d0f5ba/setup.py'"'"'; __file__='"'"'/private/var/folders/nb/_qgnfkns75bcn_p_msyjl81m0000gn/T/pip-install-r5n2ridh/shapely_58657eb7ef98443a9067e2c264d0f5ba/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/nb/_qgnfkns75bcn_p_msyjl81m0000gn/T/pip-pip-egg-info-0plvocfw
       cwd: /private/var/folders/nb/_qgnfkns75bcn_p_msyjl81m0000gn/T/pip-install-r5n2ridh/shapely_58657eb7ef98443a9067e2c264d0f5ba/
  Complete output (13 lines):
  Failed `CDLL(/Library/Frameworks/GEOS.framework/Versions/Current/GEOS)`
  Failed `CDLL(/opt/local/lib/libgeos_c.dylib)`
  Failed `CDLL(/usr/local/lib/libgeos_c.dylib)`
  Failed `CDLL(/opt/homebrew/lib/libgeos_c.dylib)`
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/private/var/folders/nb/_qgnfkns75bcn_p_msyjl81m0000gn/T/pip-install-r5n2ridh/shapely_58657eb7ef98443a9067e2c264d0f5ba/setup.py", line 74, in <module>
      from shapely._buildcfg import geos_version_string, geos_version, \
    File "/private/var/folders/nb/_qgnfkns75bcn_p_msyjl81m0000gn/T/pip-install-r5n2ridh/shapely_58657eb7ef98443a9067e2c264d0f5ba/shapely/_buildcfg.py", line 189, in <module>
      lgeos = load_dll('geos_c', fallbacks=alt_paths)
    File "/private/var/folders/nb/_qgnfkns75bcn_p_msyjl81m0000gn/T/pip-install-r5n2ridh/shapely_58657eb7ef98443a9067e2c264d0f5ba/shapely/_buildcfg.py", line 159, in load_dll
      raise OSError(
  OSError: Could not find library geos_c or load any of its variants ['/Library/Frameworks/GEOS.framework/Versions/Current/GEOS', '/opt/local/lib/libgeos_c.dylib', '/usr/local/lib/libgeos_c.dylib', '/opt/homebrew/lib/libgeos_c.dylib']
  ----------------------------------------
```

And then 1.5.10 errored with this

```
  Downloading Shapely-1.5.10.tar.gz (173 kB)
     |████████████████████████████████| 173 kB 10.0 MB/s            
  Preparing metadata (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /Library/Frameworks/Python.framework/Versions/3.10/bin/python3.10 -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/nb/_qgnfkns75bcn_p_msyjl81m0000gn/T/pip-install-r5n2ridh/shapely_a8c0c4572305473e938001bd6cfedce6/setup.py'"'"'; __file__='"'"'/private/var/folders/nb/_qgnfkns75bcn_p_msyjl81m0000gn/T/pip-install-r5n2ridh/shapely_a8c0c4572305473e938001bd6cfedce6/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/nb/_qgnfkns75bcn_p_msyjl81m0000gn/T/pip-pip-egg-info-xud71di0
       cwd: /private/var/folders/nb/_qgnfkns75bcn_p_msyjl81m0000gn/T/pip-install-r5n2ridh/shapely_a8c0c4572305473e938001bd6cfedce6/
  Complete output (5 lines):
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/private/var/folders/nb/_qgnfkns75bcn_p_msyjl81m0000gn/T/pip-install-r5n2ridh/shapely_a8c0c4572305473e938001bd6cfedce6/setup.py", line 34, in <module>
      from packaging.version import Version
  ModuleNotFoundError: No module named 'packaging'
  ----------------------------------------
```

Finally 1.5.9 installed.

Then it went down to Kraken version 2.0.8:

```
Collecting kraken
  Downloading kraken-3.0.4-py3-none-any.whl (5.4 MB)
     |████████████████████████████████| 5.4 MB 11.0 MB/s            
  Downloading kraken-3.0.2-py3-none-any.whl (5.4 MB)
     |████████████████████████████████| 5.4 MB 10.6 MB/s            
  Downloading kraken-3.0.1-py3-none-any.whl (5.5 MB)
     |████████████████████████████████| 5.5 MB 9.3 MB/s            
  Downloading kraken-2.0.8-py3-none-any.whl (643 kB)
     |████████████████████████████████| 643 kB 7.7 MB/s     
```

And a bit later to 0.9.16 again

```
Collecting kraken
  Downloading kraken-2.0.5-py3-none-any.whl (643 kB)
     |████████████████████████████████| 643 kB 12.3 MB/s            
  Downloading kraken-2.0.4-py3-none-any.whl (643 kB)
     |████████████████████████████████| 643 kB 11.0 MB/s            
  Downloading kraken-2.0.3-py3-none-any.whl (643 kB)
     |████████████████████████████████| 643 kB 11.0 MB/s            
  Downloading kraken-2.0.2-py3-none-any.whl (643 kB)
     |████████████████████████████████| 643 kB 9.8 MB/s            
  Downloading kraken-2.0.1-py2.py3-none-any.whl (642 kB)
     |████████████████████████████████| 642 kB 10.4 MB/s            
  Downloading kraken-2.0.0-py2.py3-none-any.whl (642 kB)
     |████████████████████████████████| 642 kB 12.9 MB/s            
  Downloading kraken-1.0.1-py2.py3-none-any.whl (636 kB)
     |████████████████████████████████| 636 kB 10.1 MB/s            
  Downloading kraken-1.0.0-py2.py3-none-any.whl (636 kB)
     |████████████████████████████████| 636 kB 10.1 MB/s            
  Downloading kraken-0.9.16-py2.py3-none-any.whl (595 kB)
     |████████████████████████████████| 595 kB 11.6 MB/s  
```

And then clstm fails again, with

```
Building wheels for collected packages: clstm, future
  Building wheel for clstm (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /Library/Frameworks/Python.framework/Versions/3.10/bin/python3.10 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/nb/_qgnfkns75bcn_p_msyjl81m0000gn/T/pip-install-r5n2ridh/clstm_c5a02415baf14e2e9d48bcac97a459f1/setup.py'"'"'; __file__='"'"'/private/var/folders/nb/_qgnfkns75bcn_p_msyjl81m0000gn/T/pip-install-r5n2ridh/clstm_c5a02415baf14e2e9d48bcac97a459f1/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /private/var/folders/nb/_qgnfkns75bcn_p_msyjl81m0000gn/T/pip-wheel-259nq89g
       cwd: /private/var/folders/nb/_qgnfkns75bcn_p_msyjl81m0000gn/T/pip-install-r5n2ridh/clstm_c5a02415baf14e2e9d48bcac97a459f1/
  Complete output (29 lines):
  making proto file
  Could not make proto path relative: clstm.proto: No such file or directory
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/private/var/folders/nb/_qgnfkns75bcn_p_msyjl81m0000gn/T/pip-install-r5n2ridh/clstm_c5a02415baf14e2e9d48bcac97a459f1/setup.py", line 63, in <module>
      setup(
    File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/setuptools/__init__.py", line 152, in setup
      _install_setup_requires(attrs)
    File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/setuptools/__init__.py", line 147, in _install_setup_requires
      dist.fetch_build_eggs(dist.setup_requires)
    File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/setuptools/dist.py", line 785, in fetch_build_eggs
      resolved_dists = pkg_resources.working_set.resolve(
    File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pkg_resources/__init__.py", line 766, in resolve
      dist = best[req.key] = env.best_match(
    File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pkg_resources/__init__.py", line 1051, in best_match
      return self.obtain(req, installer)
    File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pkg_resources/__init__.py", line 1063, in obtain
      return installer(requirement)
    File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/setuptools/dist.py", line 844, in fetch_build_egg
      return fetch_build_egg(self, req)
    File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/setuptools/installer.py", line 80, in fetch_build_egg
      wheel.install_as_egg(dist_location)
    File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/setuptools/wheel.py", line 95, in install_as_egg
      self._install_as_egg(destination_eggdir, zf)
    File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/setuptools/wheel.py", line 103, in _install_as_egg
      self._convert_metadata(zf, destination_eggdir, dist_info, egg_info)
    File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/setuptools/wheel.py", line 124, in _convert_metadata
      os.mkdir(destination_eggdir)
  FileExistsError: [Errno 17] File exists: '/private/var/folders/nb/_qgnfkns75bcn_p_msyjl81m0000gn/T/pip-install-r5n2ridh/clstm_c5a02415baf14e2e9d48bcac97a459f1/.eggs/numpy-1.21.4-py3.10-macosx-10.9-universal2.egg'
  ----------------------------------------
  ERROR: Failed building wheel for clstm
```

and tries to run the older method setup.py for it adn fails

```
  Running setup.py clean for clstm
  ERROR: Command errored out with exit status 1:
   command: /Library/Frameworks/Python.framework/Versions/3.10/bin/python3.10 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/nb/_qgnfkns75bcn_p_msyjl81m0000gn/T/pip-install-r5n2ridh/clstm_c5a02415baf14e2e9d48bcac97a459f1/setup.py'"'"'; __file__='"'"'/private/var/folders/nb/_qgnfkns75bcn_p_msyjl81m0000gn/T/pip-install-r5n2ridh/clstm_c5a02415baf14e2e9d48bcac97a459f1/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' clean --all
       cwd: /private/var/folders/nb/_qgnfkns75bcn_p_msyjl81m0000gn/T/pip-install-r5n2ridh/clstm_c5a02415baf14e2e9d48bcac97a459f1
  Complete output (29 lines):
  making proto file
  Could not make proto path relative: clstm.proto: No such file or directory
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/private/var/folders/nb/_qgnfkns75bcn_p_msyjl81m0000gn/T/pip-install-r5n2ridh/clstm_c5a02415baf14e2e9d48bcac97a459f1/setup.py", line 63, in <module>
      setup(
    File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/setuptools/__init__.py", line 152, in setup
      _install_setup_requires(attrs)
    File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/setuptools/__init__.py", line 147, in _install_setup_requires
      dist.fetch_build_eggs(dist.setup_requires)
    File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/setuptools/dist.py", line 785, in fetch_build_eggs
      resolved_dists = pkg_resources.working_set.resolve(
    File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pkg_resources/__init__.py", line 766, in resolve
      dist = best[req.key] = env.best_match(
    File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pkg_resources/__init__.py", line 1051, in best_match
      return self.obtain(req, installer)
    File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pkg_resources/__init__.py", line 1063, in obtain
      return installer(requirement)
    File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/setuptools/dist.py", line 844, in fetch_build_egg
      return fetch_build_egg(self, req)
    File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/setuptools/installer.py", line 80, in fetch_build_egg
      wheel.install_as_egg(dist_location)
    File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/setuptools/wheel.py", line 95, in install_as_egg
      self._install_as_egg(destination_eggdir, zf)
    File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/setuptools/wheel.py", line 103, in _install_as_egg
      self._convert_metadata(zf, destination_eggdir, dist_info, egg_info)
    File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/setuptools/wheel.py", line 124, in _convert_metadata
      os.mkdir(destination_eggdir)
  FileExistsError: [Errno 17] File exists: '/private/var/folders/nb/_qgnfkns75bcn_p_msyjl81m0000gn/T/pip-install-r5n2ridh/clstm_c5a02415baf14e2e9d48bcac97a459f1/.eggs/numpy-1.21.4-py3.10-macosx-10.9-universal2.egg'
  ----------------------------------------
  ERROR: Failed cleaning build dir for clstm
```

And finally this error

```
Installing collected packages: urllib3, six, numpy, MarkupSafe, idna, charset-normalizer, certifi, scipy, requests, regex, python-bidi, protobuf, Pillow, lxml, jinja2, future, clstm, click, kraken
    Running setup.py install for clstm ... error
    ERROR: Command errored out with exit status 1:
     command: /Library/Frameworks/Python.framework/Versions/3.10/bin/python3.10 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/nb/_qgnfkns75bcn_p_msyjl81m0000gn/T/pip-install-r5n2ridh/clstm_c5a02415baf14e2e9d48bcac97a459f1/setup.py'"'"'; __file__='"'"'/private/var/folders/nb/_qgnfkns75bcn_p_msyjl81m0000gn/T/pip-install-r5n2ridh/clstm_c5a02415baf14e2e9d48bcac97a459f1/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/nb/_qgnfkns75bcn_p_msyjl81m0000gn/T/pip-record-szkzu66y/install-record.txt --single-version-externally-managed --compile --install-headers /Library/Frameworks/Python.framework/Versions/3.10/include/python3.10/clstm
         cwd: /private/var/folders/nb/_qgnfkns75bcn_p_msyjl81m0000gn/T/pip-install-r5n2ridh/clstm_c5a02415baf14e2e9d48bcac97a459f1/
    Complete output (9 lines):
    making proto file
    Could not make proto path relative: clstm.proto: No such file or directory
    running install
    running build
    running build_ext
    building '_clstm' extension
    swigging clstm.i to clstm_wrap.cpp
    swig -python -c++ -I/Library/Frameworks/Python.framework/Versions/3.10/include/python3.10 -I/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/numpy/core/include -o clstm_wrap.cpp clstm.i
    error: command 'swig' failed: No such file or directory
    ----------------------------------------
ERROR: Command errored out with exit status 1: /Library/Frameworks/Python.framework/Versions/3.10/bin/python3.10 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/nb/_qgnfkns75bcn_p_msyjl81m0000gn/T/pip-install-r5n2ridh/clstm_c5a02415baf14e2e9d48bcac97a459f1/setup.py'"'"'; __file__='"'"'/private/var/folders/nb/_qgnfkns75bcn_p_msyjl81m0000gn/T/pip-install-r5n2ridh/clstm_c5a02415baf14e2e9d48bcac97a459f1/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/nb/_qgnfkns75bcn_p_msyjl81m0000gn/T/pip-record-szkzu66y/install-record.txt --single-version-externally-managed --compile --install-headers /Library/Frameworks/Python.framework/Versions/3.10/include/python3.10/clstm Check the logs for full command output.
```

So I wonder what is going on. Did I miss a prerequisite?
I have `kraken 2.0.8` running under Python 3.9. And there it does not need clstm anyway.
And under 3.9 I can upgrade it to 3.0.6 by

```
pip3 install --upgrade 'kraken>=3'
```

**Comment by dirkroorda** [comment]
It could be this: torch does not install (yet) under python3.10 and it is a dependency of Kraken.
I guess I just have to wait.

I should have done this, from the outset, which would have saved me considerable time:

```
pip3 install 'kraken>=3'
```

which tells me outright:

```
ERROR: Cannot install kraken==3.0.1, kraken==3.0.2, kraken==3.0.4 and kraken==3.0.6 because these package versions have conflicting dependencies.

The conflict is caused by:
    kraken 3.0.6 depends on torchvision>=0.5.0
    kraken 3.0.4 depends on torchvision>=0.5.0
    kraken 3.0.2 depends on torchvision>=0.5.0
    kraken 3.0.1 depends on torchvision>=0.5.0

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/user_guide/#fixing-conflicting-dependencies
```

**Comment by dirkroorda** [comment]
All in all it is more a problem of the pip installation procedure than of the kraken software.

Yet I think it is helpful to put a warning in the installation docs of Kraken. 
Maybe suggest to install torch separately before trying to install Kraken.
Or to suggest to install Kraken with a minimum version specifier.
Torch is known to be slow in having a build for a new Python version.
Now I think of it, I had something like this before, when installing it under Python3.9.
And this will happen again at Python 3.11.

**Comment by mittagessen** [comment]
This is an issue caused by the bi-weekly changes to python packaging. In the past there was no real way to indicate which interpreter version a package is compatible with for universal builds that are compatible both with 2.7 and 3.x. Kraken stopped supporting 2.7 a long time ago and the supported python versions are since then explicitly encoded in `setup.cfg`. 3.10 is obviously not supported as dependencies are missing (and this is correctly configured for both pypi and anaconda packages) so pip goes back down the history until it stumbles upon the old universal packages.

The correct thing is to yank all the old releases (on it right now) that (hopefully) no one is using anymore anyway. This should allow pip to actually return the dependency conflict. Why doesn't it just abort when trying to install a package with an in compatible interpreter version? No idea.

**Comment by mittagessen** [comment]
Arrrgh, I only set it in the metadata classifiers and not in the `python_requires` field of the project metadata. It will still abort now after trying to download all the older releases but with a less informative error message than with correct runtime environment restrictions. Unfortunately, I can't yank those releases as they are in active use and in the pinned requirements of other projects.
