### ISSUE TITLE
Training a new model for telugu language fails

### ISSUE THREAD

**Issue by ChillarAnand** [mittagessen/kraken#32]
I am trying to train ocropy model for telugu language. 10 samples of training data is [available here](https://www.dropbox.com/s/toj8wov9n3ccrgj/train_te.zip) 

When I try to run it fails with different errors

```
chillaranand@pavilion:~/projects/python/ocr/data/samples |
→ ketos linegen 0000.gt.txt
Reading texts   ✓
Read 1 unique lines
Σ (len: 22)
Symbols:  ంఇఉకటడణదనబమరసహాిుెేొ
Combining Characters: TELUGU SIGN VIRAMA
Writing images  ⣽/home/chillaranand/.virtualenvs/p35/lib/python3.5/site-packages/kraken/linegen.py:278: VisibleDeprecationWarning: using a non-integer
 number instead of an integer will result in an error in the future                                                                                  
  hs = gaussian_filter(np.random.randn(4*h, 1.5*w), sigma)
/home/chillaranand/.virtualenvs/p35/lib/python3.5/site-packages/kraken/linegen.py:279: VisibleDeprecationWarning: using a non-integer number instead o
f an integer will result in an error in the future                                                                                                   
  ws = gaussian_filter(np.random.randn(4*h, 1.5*w), sigma)
Traceback (most recent call last):
  File "/home/chillaranand/.virtualenvs/p35/bin/ketos", line 11, in <module>
    sys.exit(cli())
  File "/home/chillaranand/.virtualenvs/p35/lib/python3.5/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/home/chillaranand/.virtualenvs/p35/lib/python3.5/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/home/chillaranand/.virtualenvs/p35/lib/python3.5/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/chillaranand/.virtualenvs/p35/lib/python3.5/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/chillaranand/.virtualenvs/p35/lib/python3.5/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/home/chillaranand/.virtualenvs/p35/lib/python3.5/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/chillaranand/.virtualenvs/p35/lib/python3.5/site-packages/kraken/ketos.py", line 407, in line_generator
    im = linegen.degrade_line(im, np.random.normal(mean), np.random.normal(sigma), np.random.normal(density))
  File "/home/chillaranand/.virtualenvs/p35/lib/python3.5/site-packages/kraken/linegen.py", line 239, in degrade_line
    im += np.random.normal(mean, sigma, im.shape)
  File "mtrand.pyx", line 1902, in mtrand.RandomState.normal (numpy/random/mtrand/mtrand.c:17755)
ValueError: scale <= 0
```

For another file, it throws this error

```
chillaranand@pavilion:~/projects/python/ocr/data/samples |
→ ketos linegen 0002.gt.txt
Reading texts   ✓
Read 1 unique lines
Σ (len: 23)
Symbols:  ంఅచజడతదనపభమయరలవాిీుెో
Combining Characters: TELUGU SIGN VIRAMA
Writing images  ⣽/home/chillaranand/.virtualenvs/p35/lib/python3.5/site-packages/kraken/linegen.py:278: VisibleDeprecationWarning: using a non-integer
 number instead of an integer will result in an error in the future                                                                                  
  hs = gaussian_filter(np.random.randn(4*h, 1.5*w), sigma)
/home/chillaranand/.virtualenvs/p35/lib/python3.5/site-packages/kraken/linegen.py:279: VisibleDeprecationWarning: using a non-integer number instead o
f an integer will result in an error in the future                                                                                                   
  ws = gaussian_filter(np.random.randn(4*h, 1.5*w), sigma)
Traceback (most recent call last):
  File "/home/chillaranand/.virtualenvs/p35/bin/ketos", line 11, in <module>
    sys.exit(cli())
  File "/home/chillaranand/.virtualenvs/p35/lib/python3.5/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/home/chillaranand/.virtualenvs/p35/lib/python3.5/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/home/chillaranand/.virtualenvs/p35/lib/python3.5/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/chillaranand/.virtualenvs/p35/lib/python3.5/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/chillaranand/.virtualenvs/p35/lib/python3.5/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/home/chillaranand/.virtualenvs/p35/lib/python3.5/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/chillaranand/.virtualenvs/p35/lib/python3.5/site-packages/kraken/ketos.py", line 407, in line_generator
    im = linegen.degrade_line(im, np.random.normal(mean), np.random.normal(sigma), np.random.normal(density))
  File "/home/chillaranand/.virtualenvs/p35/lib/python3.5/site-packages/kraken/linegen.py", line 241, in degrade_line
    coords = [np.random.randint(0, i - 1, int(flipped)) for i in im.shape]
  File "/home/chillaranand/.virtualenvs/p35/lib/python3.5/site-packages/kraken/linegen.py", line 241, in <listcomp>
    coords = [np.random.randint(0, i - 1, int(flipped)) for i in im.shape]
  File "mtrand.pyx", line 1266, in mtrand.RandomState.randint (numpy/random/mtrand/mtrand.c:14292)
  File "mtrand.pyx", line 1267, in mtrand.RandomState.randint (numpy/random/mtrand/mtrand.c:14131)
  File "mtrand.pyx", line 749, in mtrand._rand_int64 (numpy/random/mtrand/mtrand.c:9764)
ValueError: negative dimensions are not allowed
```

Any ideas on how to fix this?

**Comment by mittagessen** [comment]
Are you trying to train a new model or generate artificial training data (and then training a model) from Telugu texts? In the first case you wouldn't need to generate lines but would just run clstmocrtrain tool from clstm to generate a new model. For the second case there's a bug caused by negative floats returned by sampling the normal distribution (duh). I'll fix it momentarily.

**Comment by ChillarAnand** [comment]
>  a bug caused by negative floats returned by sampling the normal distribution (duh). I'll fix it momentarily.

This one. Please fix it whenever you have time. Thanks.
