### ISSUE TITLE
Boundary tracing failed

### ISSUE THREAD

**Issue by stweil** [mittagessen/kraken#367]
This image triggers a segmentation warning:
https://digi.bib.uni-mannheim.de/fileadmin/digi/477366015/max/477366015_0112.jpg.
```
$ kraken -x -I 477366015_0112.jpg -o .xml segment -bl ocr -m luther.mlmodel 
WARNING:root:Torch version 1.11.0+cu102 has not been tested with coremltools. You may run into unexpected errors. Torch 1.10.2 is the most recent version that has been tested.
Loading ANN /luther/venv3.9/lib/python3.9/site-packages/kraken/blla.mlmodel ✓
Loading ANN default     ✓
Segmenting      [07/04/22 12:54:19] WARNING  Boundary tracing failed in baseline elongation: index 1 is out of bounds for axis 0 with size 1                                     segmentation.py:220
✓
Processing ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 37/37 0:00:00 0:00:10
Writing recognition results for 477366015_0112.jpg  ✓
```

Stacktrace:
```
Traceback (most recent call last):
  File "/home/stweil/luther/venv3.9/lib/python3.9/site-packages/kraken/lib/segmentation.py", line 217, in _extend_boundaries
    b = boundary_tracing(x)
  File "/home/stweil/luther/venv3.9/lib/python3.9/site-packages/kraken/lib/segmentation.py", line 177, in boundary_tracing
    start = [y[idx_start], x[idx_start]]
IndexError: index 1 is out of bounds for axis 0 with size 1
```

**Comment by mittagessen** [comment]
Yeah, that's just a warning for a region that has a too small area to compute the boundary. It can probably be ignored (and I can't even reproduce it on my system).
