### ISSUE TITLE
Broken file mode

### ISSUE THREAD

**Issue by Afterburned6387** [mittagessen/kraken#40]
Attempted to run the example shown in the documentation. Got this:

```
kraken -i page-00000.tiff out.html binarize segment ocr -h
Loading RNN	✓
Binarizing	✓
Segmenting	Traceback (most recent call last):
  File "/usr/local/bin/kraken", line 10, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1093, in invoke
    return _process_result(rv)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1031, in _process_result
    **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/Users/parkerhancock/Projects/kraken/kraken/kraken.py", line 142, in process_pipeline
    task(base_image=base_image, input=input, output=output)
  File "/Users/parkerhancock/Projects/kraken/kraken/kraken.py", line 81, in segmenter
    json.dump(res, fp)
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/__init__.py", line 180, in dump
    fp.write(chunk)
TypeError: a bytes-like object is required, not 'str'
```
Pulled the repo, and found the culprit. On line 80, the "open" command needs to be changed from "wb" to "w". 

The json.dump method returns a string, which raises an error when it attempts to write it to a file opened in binary mode. I have a branch if you want to make this a pull request, but it's just one line to fix. Have it installed editable on my machine with the change, but it would be super-handy if you could make it to the repo version. 

Running on Python 3.6.1

Thanks!

**Comment by mittagessen** [comment]
Thanks for pointing that out. I should really get around to write some unit tests for the CLI.
