### ISSUE TITLE
Recursion Error during training

### ISSUE THREAD

**Issue by lauxley** [mittagessen/kraken#403]
During a integration unit test with kraken (with crap data):

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/kraken/lib/dataset.py", line 784, in __getitem__
    im, _ = next(extract_polygons(im, {'type': 'baselines',
  File "/usr/local/lib/python3.8/site-packages/kraken/lib/segmentation.py", line 959, in extract_polygons
    raise KrakenInputException('Line polygon outside of image bounds')
kraken.lib.exceptions.KrakenInputException: Line polygon outside of image bounds
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/kraken/lib/dataset.py", line 784, in __getitem__
    im, _ = next(extract_polygons(im, {'type': 'baselines',
  File "/usr/local/lib/python3.8/site-packages/kraken/lib/segmentation.py", line 959, in extract_polygons
    raise KrakenInputException('Line polygon outside of image bounds')
kraken.lib.exceptions.KrakenInputException: Line polygon outside of image bounds
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/builds/scripta/escriptorium/app/apps/core/tasks.py", line 508, in train
    train_(qs, document, transcription, model=model, user=user)
  File "/builds/scripta/escriptorium/app/apps/core/tasks.py", line 464, in train_
    trainer.fit(kraken_model)
  File "/usr/local/lib/python3.8/site-packages/kraken/lib/train.py", line 95, in fit
    super().fit(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 770, in fit
    self._call_and_handle_interrupt(
  File "/usr/local/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 723, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 811, in _fit_impl
    results = self._run(model, ckpt_path=self.ckpt_path)
  File "/usr/local/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1236, in _run
    results = self._run_stage()
  File "/usr/local/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1323, in _run_stage
    return self._run_train()
  File "/usr/local/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1345, in _run_train
    self._run_sanity_check()
  File "/usr/local/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1413, in _run_sanity_check
    val_loop.run()
  File "/usr/local/lib/python3.8/site-packages/pytorch_lightning/loops/base.py", line 204, in run
    self.advance(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/pytorch_lightning/loops/dataloader/evaluation_loop.py", line 155, in advance
    dl_outputs = self.epoch_loop.run(self._data_fetcher, dl_max_batches, kwargs)
  File "/usr/local/lib/python3.8/site-packages/pytorch_lightning/loops/base.py", line 204, in run
    self.advance(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/pytorch_lightning/loops/epoch/evaluation_epoch_loop.py", line 112, in advance
    batch = next(data_fetcher)
  File "/usr/local/lib/python3.8/site-packages/pytorch_lightning/utilities/fetching.py", line 184, in __next__
    return self.fetching_function()
  File "/usr/local/lib/python3.8/site-packages/pytorch_lightning/utilities/fetching.py", line 259, in fetching_function
    self._fetch_next_batch(self.dataloader_iter)
  File "/usr/local/lib/python3.8/site-packages/pytorch_lightning/utilities/fetching.py", line 273, in _fetch_next_batch
    batch = next(iterator)
  File "/usr/local/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 530, in __next__
    data = self._next_data()
  File "/usr/local/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 570, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/usr/local/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/usr/local/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/usr/local/lib/python3.8/site-packages/torch/utils/data/dataset.py", line 471, in __getitem__
    return self.dataset[self.indices[idx]]
  File "/usr/local/lib/python3.8/site-packages/kraken/lib/dataset.py", line 806, in __getitem__
    return self[idx]
  File "/usr/local/lib/python3.8/site-packages/kraken/lib/dataset.py", line 806, in __getitem__
    return self[idx]
  File "/usr/local/lib/python3.8/site-packages/kraken/lib/dataset.py", line 806, in __getitem__
    return self[idx]
  **[Previous line repeated 297 more times]**
  File "/usr/local/lib/python3.8/site-packages/kraken/lib/dataset.py", line 804, in __getitem__
    logger.debug(traceback.format_exc())
  File "/usr/local/lib/python3.8/traceback.py", line 167, in format_exc
    return "".join(format_exception(*sys.exc_info(), limit=limit, chain=chain))
  File "/usr/local/lib/python3.8/traceback.py", line 120, in format_exception
    return list(TracebackException(
  File "/usr/local/lib/python3.8/traceback.py", line 493, in __init__
    context = TracebackException(
  File "/usr/local/lib/python3.8/traceback.py", line 493, in __init__
    context = TracebackException(
  File "/usr/local/lib/python3.8/traceback.py", line 493, in __init__
    context = TracebackException(
  [Previous line repeated 297 more times]
  File "/usr/local/lib/python3.8/traceback.py", line 476, in __init__
    _seen.add(id(exc_value))
RecursionError: maximum recursion depth exceeded while calling a Python object
```

**Comment by mittagessen** [comment]
Hmm, that happens when the line extractions fails as the sample gets automatically replaced by another which I guess is also broken so it keeps doing that until the recursion depth is exceeded. I could probably add a counter to abort after a certain number of failures but it will probably break some training behavior that used to work.

**Comment by lauxley** [comment]
Ok I'll try to fix the test data instead then, thanks.
