### ISSUE TITLE
TypeError: a bytes-like object is required, not 'str'

### ISSUE THREAD

**Issue by MohandesaliRahnema** [mittagessen/kraken#51]
hi i have the following error when i issue bellow command:
kraken -i image.png image.txt binarize segment ocr
Loading RNN	✓
Binarizing	✓
Segmenting	Traceback (most recent call last):
  File "/home/rahnema/anaconda3/bin/kraken", line 11, in <module>
    sys.exit(cli())
  File "/home/rahnema/anaconda3/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/rahnema/anaconda3/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/rahnema/anaconda3/lib/python3.6/site-packages/click/core.py", line 1093, in invoke
    return _process_result(rv)
  File "/home/rahnema/anaconda3/lib/python3.6/site-packages/click/core.py", line 1031, in _process_result
    **ctx.params)
  File "/home/rahnema/anaconda3/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/rahnema/anaconda3/lib/python3.6/site-packages/kraken/kraken.py", line 142, in process_pipeline
    task(base_image=base_image, input=input, output=output)
  File "/home/rahnema/anaconda3/lib/python3.6/site-packages/kraken/kraken.py", line 81, in segmenter
    json.dump(res, fp)
  File "/home/rahnema/anaconda3/lib/python3.6/json/__init__.py", line 180, in dump
    fp.write(chunk)
TypeError: a bytes-like object is required, not 'str'

**Comment by mittagessen** [comment]
Which version of kraken are you running? I remember there being a regression in python 3 support in the segmentation code (where this is happening) in the past and I can't reproduce the error (it is fairly straightforward with json.dump with str output being written to a file opened in binary mode).

**Comment by MohandesaliRahnema** [comment]
hi i am using last version from git hub
my python version is 3.7
but i cant understand how can i solve it?
