### ISSUE TITLE
Failure using pip install kraken

### ISSUE THREAD

**Issue by christophered** [mittagessen/kraken#56]
Peace be upon you
Trying to install Kraken on a fresh Ubuntu 16.04

- Using `pip install kraken` & `sudo pip install kraken`, results after installation:
The program 'kraken' is currently not installed.

- Using `pip install -U pip setuptools` and `sudo apt install build-essential python-dev` and `pip install kraken`, results after installation:
Kraken command can be issued but using any clstm model fails.
Video demonstration: [https://youtu.be/Myv25XE11lM](https://youtu.be/Myv25XE11lM)
Log:
```chris@ubuntu:~/Desktop/test$ kraken -i 000000.png out.txt binarize segment ocr -m arabic-beirut.clstm 
Loading RNN default	✗
Traceback (most recent call last):
  File "/usr/local/bin/kraken", line 11, in <module>
    sys.exit(cli())
  File "/home/chris/.local/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/chris/.local/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/chris/.local/lib/python2.7/site-packages/click/core.py", line 1092, in invoke
    rv.append(sub_ctx.command.invoke(sub_ctx))
  File "/home/chris/.local/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/chris/.local/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/chris/.local/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/kraken/kraken.py", line 262, in ocr
    rnn = models.load_any(location)
  File "/usr/local/lib/python2.7/dist-packages/kraken/lib/models.py", line 213, in load_any
    seq = load_pyrnn(fname)
  File "/usr/local/lib/python2.7/dist-packages/kraken/lib/models.py", line 320, in load_pyrnn
    raise KrakenInvalidModelException(str(e))
kraken.lib.exceptions.KrakenInvalidModelException: invalid load key, '

**Comment by mittagessen** [comment]
The first error is probably caused by not having all prerequisites as listed on ``http://kraken.re`` installed. After installing python-dev (as indicated in the documentation) the installation succeeded.

To load clstm models you have to install the clstm python binding. Without them only pyrnn and pronn-type models can be used and the script detection in the segmenter will be disabled.

**Comment by christophered** [comment]
"clstm python bindings" seems like Valyrian language to me :sunglasses:  and yes, it's a `Game of Thrones` reference.
@mittagessen I have managed to build clstm, you can have a look at https://youtu.be/ST_XrfcCpKE
Now how can I install the clstm python bindings?
Also what do you think about #57

**Comment by christophered** [comment]
I installed the dependencies fully, and rebuilt clstm and kraken, but I dont know how to install the clstm bindings.

The newer error log is:
```u@ubuntu:~/Desktop/Final html/output_directory$ kraken -i 000000.png out.txt binarize segment ocr -m arabic-2000.clstm 
Loading RNN default	✓
Binarizing	✓
Segmenting	✓
Traceback (most recent call last):
  File "/usr/local/bin/kraken", line 11, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 1093, in invoke
    return _process_result(rv)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 1031, in _process_result
    **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/kraken/kraken.py", line 161, in process_pipeline
    task(base_image=base_image, input=input, output=output)
  File "/usr/local/lib/python2.7/dist-packages/kraken/kraken.py", line 119, in recognizer
    for pred in it:
  File "/usr/local/lib/python2.7/dist-packages/kraken/rpred.py", line 193, in mm_rpred
    'boxes': map(lambda x: x[1], line)})):
  File "/usr/local/lib/python2.7/dist-packages/kraken/rpred.py", line 133, in extract_boxes
    raise KrakenInputException('Line outside of image bounds')
kraken.lib.exceptions.KrakenInputException: Line outside of image bounds

**Comment by christophered** [comment]
@bmwmy  can you help, how can I build and install kraken.
I have built clstm separate derv successfully, and have all the required dependencies, how can i install kraken?

**Comment by bmwmy** [comment]
@christophered I think it is better to install thru git repository (you have to use git for downloading

git clone https://github.com/mittagessen/kraken.git
Then just run the setup.py file from that directory,
sudo python setup.py install

**Comment by christophered** [comment]
@bmwmy 
```
chris@ubuntu:~/Desktop/kraken-master$ sudo -H pip install .
[sudo] password for chris: 
Processing /home/chris/Desktop/kraken-master
    Complete output from command python setup.py egg_info:
    
    Installed /tmp/pip-Jh9gW5-build/.eggs/pbr-3.1.1-py2.7.egg
    ERROR:root:Error parsing
    Traceback (most recent call last):
      File "/tmp/pip-Jh9gW5-build/.eggs/pbr-3.1.1-py2.7.egg/pbr/core.py", line 111, in pbr
        attrs = util.cfg_to_args(path, dist.script_args)
      File "/tmp/pip-Jh9gW5-build/.eggs/pbr-3.1.1-py2.7.egg/pbr/util.py", line 249, in cfg_to_args
        pbr.hooks.setup_hook(config)
      File "/tmp/pip-Jh9gW5-build/.eggs/pbr-3.1.1-py2.7.egg/pbr/hooks/__init__.py", line 25, in setup_hook
        metadata_config.run()
      File "/tmp/pip-Jh9gW5-build/.eggs/pbr-3.1.1-py2.7.egg/pbr/hooks/base.py", line 27, in run
        self.hook()
      File "/tmp/pip-Jh9gW5-build/.eggs/pbr-3.1.1-py2.7.egg/pbr/hooks/metadata.py", line 26, in hook
        self.config['name'], self.config.get('version', None))
      File "/tmp/pip-Jh9gW5-build/.eggs/pbr-3.1.1-py2.7.egg/pbr/packaging.py", line 755, in get_version
        name=package_name))
    Exception: Versioning for this project requires either an sdist tarball, or access to an upstream git repository. It's also possible that there is a mismatch between the package name in setup.cfg and the argument given to pbr.version.VersionInfo. Project name kraken was given, but was not able to be found.
    error in setup command: Error parsing /tmp/pip-Jh9gW5-build/setup.cfg: Exception: Versioning for this project requires either an sdist tarball, or access to an upstream git repository. It's also possible that there is a mismatch between the package name in setup.cfg and the argument given to pbr.version.VersionInfo. Project name kraken was given, but was not able to be found.
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-Jh9gW5-build/
You are using pip version 8.1.1, however version 9.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command

**Comment by christophered** [comment]
```chris@ubuntu:~/Desktop/kraken-master$ sudo python setup.py install
[sudo] password for chris: 

Installed /home/chris/Desktop/kraken-master/.eggs/pbr-3.1.1-py2.7.egg
ERROR:root:Error parsing
Traceback (most recent call last):
  File "/home/chris/Desktop/kraken-master/.eggs/pbr-3.1.1-py2.7.egg/pbr/core.py", line 111, in pbr
    attrs = util.cfg_to_args(path, dist.script_args)
  File "/home/chris/Desktop/kraken-master/.eggs/pbr-3.1.1-py2.7.egg/pbr/util.py", line 249, in cfg_to_args
    pbr.hooks.setup_hook(config)
  File "/home/chris/Desktop/kraken-master/.eggs/pbr-3.1.1-py2.7.egg/pbr/hooks/__init__.py", line 25, in setup_hook
    metadata_config.run()
  File "/home/chris/Desktop/kraken-master/.eggs/pbr-3.1.1-py2.7.egg/pbr/hooks/base.py", line 27, in run
    self.hook()
  File "/home/chris/Desktop/kraken-master/.eggs/pbr-3.1.1-py2.7.egg/pbr/hooks/metadata.py", line 26, in hook
    self.config['name'], self.config.get('version', None))
  File "/home/chris/Desktop/kraken-master/.eggs/pbr-3.1.1-py2.7.egg/pbr/packaging.py", line 755, in get_version
    name=package_name))
Exception: Versioning for this project requires either an sdist tarball, or access to an upstream git repository. It's also possible that there is a mismatch between the package name in setup.cfg and the argument given to pbr.version.VersionInfo. Project name kraken was given, but was not able to be found.
error in setup command: Error parsing /home/chris/Desktop/kraken-master/setup.cfg: Exception: Versioning for this project requires either an sdist tarball, or access to an upstream git repository. It's also possible that there is a mismatch between the package name in setup.cfg and the argument given to pbr.version.VersionInfo. Project name kraken was given, but was not able to be found.

**Comment by christophered** [comment]
```
chris@ubuntu:~/Desktop/Untitled Folder/kraken$ sudo -H pip install .
[sudo] password for chris: 
Processing /home/chris/Desktop/Untitled Folder/kraken
Requirement already satisfied (use --upgrade to upgrade): lxml in /usr/local/lib/python2.7/dist-packages (from kraken===0.9.4)
Requirement already satisfied (use --upgrade to upgrade): future in /usr/local/lib/python2.7/dist-packages (from kraken===0.9.4)
Requirement already satisfied (use --upgrade to upgrade): requests in /usr/local/lib/python2.7/dist-packages (from kraken===0.9.4)
Requirement already satisfied (use --upgrade to upgrade): click>=5.0 in /usr/local/lib/python2.7/dist-packages (from kraken===0.9.4)
Requirement already satisfied (use --upgrade to upgrade): numpy in /usr/lib/python2.7/dist-packages (from kraken===0.9.4)
Requirement already satisfied (use --upgrade to upgrade): Pillow in /usr/local/lib/python2.7/dist-packages (from kraken===0.9.4)
Requirement already satisfied (use --upgrade to upgrade): regex in /usr/local/lib/python2.7/dist-packages (from kraken===0.9.4)
Requirement already satisfied (use --upgrade to upgrade): scipy in /usr/local/lib/python2.7/dist-packages (from kraken===0.9.4)
Requirement already satisfied (use --upgrade to upgrade): protobuf>=3.0.0 in /usr/local/lib/python2.7/dist-packages (from kraken===0.9.4)
Requirement already satisfied (use --upgrade to upgrade): jinja2 in /usr/local/lib/python2.7/dist-packages (from kraken===0.9.4)
Requirement already satisfied (use --upgrade to upgrade): python-bidi in /usr/local/lib/python2.7/dist-packages (from kraken===0.9.4)
Requirement already satisfied (use --upgrade to upgrade): idna<2.6,>=2.5 in /usr/local/lib/python2.7/dist-packages (from requests->kraken===0.9.4)
Requirement already satisfied (use --upgrade to upgrade): urllib3<1.22,>=1.21.1 in /usr/local/lib/python2.7/dist-packages (from requests->kraken===0.9.4)
Requirement already satisfied (use --upgrade to upgrade): chardet<3.1.0,>=3.0.2 in /usr/local/lib/python2.7/dist-packages (from requests->kraken===0.9.4)
Requirement already satisfied (use --upgrade to upgrade): certifi>=2017.4.17 in /usr/local/lib/python2.7/dist-packages (from requests->kraken===0.9.4)
Requirement already satisfied (use --upgrade to upgrade): olefile in /usr/local/lib/python2.7/dist-packages (from Pillow->kraken===0.9.4)
Requirement already satisfied (use --upgrade to upgrade): six>=1.9 in /usr/lib/python2.7/dist-packages (from protobuf>=3.0.0->kraken===0.9.4)
Requirement already satisfied (use --upgrade to upgrade): setuptools in /usr/lib/python2.7/dist-packages (from protobuf>=3.0.0->kraken===0.9.4)
Requirement already satisfied (use --upgrade to upgrade): MarkupSafe>=0.23 in /usr/local/lib/python2.7/dist-packages (from jinja2->kraken===0.9.4)
Installing collected packages: kraken
  Running setup.py install for kraken ... done
Successfully installed kraken-0.9.4
You are using pip version 8.1.1, however version 9.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.

**Comment by christophered** [comment]
@bmwmy when I try using a model for recognition 
```
chris@ubuntu:~/Desktop/Untitled Folder 2$ kraken -i 000850.png out.txt binarize segment ocr -m arabic-3000.clstm 
Loading RNN default	✗
Traceback (most recent call last):
  File "/usr/local/bin/kraken", line 10, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 1092, in invoke
    rv.append(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/kraken/kraken.py", line 262, in ocr
    rnn = models.load_any(location)
  File "/usr/local/lib/python2.7/dist-packages/kraken/lib/models.py", line 213, in load_any
    seq = load_pyrnn(fname)
  File "/usr/local/lib/python2.7/dist-packages/kraken/lib/models.py", line 320, in load_pyrnn
    raise KrakenInvalidModelException(str(e))
kraken.lib.exceptions.KrakenInvalidModelException: invalid load key, '
'.

**Comment by christophered** [comment]
```
chris@ubuntu:~/Desktop/Untitled Folder$ kraken -i 000000.png out.txt binarize segment ocr -m arabic-34000.clstm 
Loading RNN default	✓
Binarizing	✓
Segmenting	✓
Traceback (most recent call last):
  File "/usr/local/bin/kraken", line 10, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 1093, in invoke
    return _process_result(rv)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 1031, in _process_result
    **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/kraken/kraken.py", line 161, in process_pipeline
    task(base_image=base_image, input=input, output=output)
  File "/usr/local/lib/python2.7/dist-packages/kraken/kraken.py", line 119, in recognizer
    for pred in it:
  File "/usr/local/lib/python2.7/dist-packages/kraken/rpred.py", line 193, in mm_rpred
    'boxes': map(lambda x: x[1], line)})):
  File "/usr/local/lib/python2.7/dist-packages/kraken/rpred.py", line 133, in extract_boxes
    raise KrakenInputException('Line outside of image bounds')
kraken.lib.exceptions.KrakenInputException: Line outside of image bounds

**Comment by christophered** [comment]
I will reply soon, i think it worked

**Comment by christophered** [comment]
@mittagessen @bmwmy when I install and use Kraken versions 0.9.1 or 0.9.2 I can use clstm models for All languages successfully and without errors.
But when using Kraken versions 0.9.3 or 0.9.4 it can only recognize English clstm models, and If I use Arabic models for recognition [it fails with an error posted at top](https://github.com/mittagessen/kraken/issues/56#issuecomment-316850764)
versions 0.9.3 and 0.9.4 can't recognize Arabic
My Arabic trained model [arabic-75000.zip](https://github.com/mittagessen/kraken/files/1174384/arabic-75000.zip)

**Comment by christophered** [comment]
The problem came out to be caused by Kraken versions 0.93 and 0.9.4
#60
