### ISSUE TITLE
No Arabic recognition in Kraken version 0.9.4

### ISSUE THREAD

**Issue by ghost** [mittagessen/kraken#60]
Hi there,
When using Arabic clstm models in Kraken versions 0.9.3 or 0.9.4 an error appears at the ocr step.
Note that version 0.9.4 and 0.9.3 can use English models without problems, and also note that earlier versions don't have this problem with Arabic.
[The Arabic clstm model arabic-75000.zip](https://github.com/mittagessen/kraken/files/1174436/arabic-75000.zip)
```
chris@ubuntu:~/Desktop/Untitled Folder$ kraken -i 000002.png out.txt binarize segment ocr -m arabic-75000.clstm
Loading RNN default	✓
Binarizing	✓
Segmenting	✓
Traceback (most recent call last):
  File "/usr/local/bin/kraken", line 10, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 1093, in invoke
    return _process_result(rv)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 1031, in _process_result
    **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/kraken/kraken.py", line 161, in process_pipeline
    task(base_image=base_image, input=input, output=output)
  File "/usr/local/lib/python2.7/dist-packages/kraken/kraken.py", line 119, in recognizer
    for pred in it:
  File "/usr/local/lib/python2.7/dist-packages/kraken/rpred.py", line 193, in mm_rpred
    'boxes': map(lambda x: x[1], line)})):
  File "/usr/local/lib/python2.7/dist-packages/kraken/rpred.py", line 133, in extract_boxes
    raise KrakenInputException('Line outside of image bounds')
kraken.lib.exceptions.KrakenInputException: Line outside of image bounds

**Comment by christophered** [comment]
@mittagessen were you able to have a look at this issue?

**Comment by christophered** [comment]
The bug continues on the latest version 0.9.5 but getting a different error when trying an Arabic clstm model:
```
chris@ubuntu:~/Desktop/Test$ kraken -i wer.png out.txt binarize segment ocr -m arabic-75000.clstm 
Loading RNN default	✓
Binarizing	✓
Segmenting	✓
Traceback (most recent call last):
  File "/usr/local/bin/kraken", line 10, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 1093, in invoke
    return _process_result(rv)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 1031, in _process_result
    **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/kraken/kraken.py", line 167, in process_pipeline
    task(base_image=base_image, input=input, output=output)
  File "/usr/local/lib/python2.7/dist-packages/kraken/kraken.py", line 125, in recognizer
    for pred in it:
  File "/usr/local/lib/python2.7/dist-packages/kraken/rpred.py", line 193, in mm_rpred
    'boxes': map(lambda x: x[1], line)})):
  File "/usr/local/lib/python2.7/dist-packages/kraken/rpred.py", line 133, in extract_boxes
    raise KrakenInputException('Line outside of image bounds')
kraken.lib.exceptions.KrakenInputException: Line outside of image bounds

**Comment by christophered** [comment]
@mittagessen I am waiting for you to solve this issue, so that I can start building Arabic CLSTM models with high `hidden` values, each model for a different font: Arial, Times New Roman, Sans Serif, etc......
Which will be later added to the Kraken model repository.

Do you suggest that I mix multiple fonts in the training data?
Or is it better that I make a different model for each font?

**Comment by christophered** [comment]
is there a particular Eigen version that I should use?

**Comment by christophered** [comment]
@mittagessen have you figured out the problem?

**Comment by mittagessen** [comment]
I apologize for not getting back to you sooner. The model works perfectly fine although I can't attest to its quality. The issues seems to be in the segmenter and I suspect you're trying to recognize aberrant data by segmenting a single line and feeding the broken results into the recognizer.  Try looking at the output of ``kraken segment`` and change it to a single bounding box of the line image size to recognize single lines (or use the API).
