### ISSUE TITLE
dict object has no attribute 'iteritems'

### ISSUE THREAD

**Issue by JmiXIII** [mittagessen/kraken#64]
Hello I tried this : kraken -i dwg.jpg convertex.txt binarize segment ocr
but got an error dict object has no attribute 'iteritems'. 

In kraken.py =>  for k, v in model.iteritems(): 
I tried several image input (jpg, png) with the same issues...

kraken has been installed through pip install kraken on anconda python (V3.5.3 64bits)

**Comment by mittagessen** [comment]
My first guess would be something going awry with the python-future as it should install aliases to make the python2 iteritems work on python3. Could you try the latest commit and see if the error disappears?

**Comment by JmiXIII** [comment]
Hi,
Directly modified in sites packages cause I do not manage to pip install in the git downloaded folder (but I'm not used to this)
The error does not appears anymore but I'm not getting the following error : 
File "c:\users\user11.hpo-samat\appdata\local\continuum\anaconda3\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x8f in position 230: character maps to <undefined>
![output](https://user-images.githubusercontent.com/13539415/31169650-a03c6028-a8f9-11e7-93cd-3da8602f6bc7.png)

**Comment by mittagessen** [comment]
OK, can you send me the complete stack trace? It should show something along the line "path/path/kraken/somefile.py"", line XX ...? In general software tends to break by now if your system locale doesn't use Unicode/UTF-8, so changing that might be all that's necessary. Even if it is an kraken bug you'll probably run into similar issues with other packages sooner rather than later.

**Comment by JmiXIII** [comment]
Hello,

I made the same op on both computer (windows + linux) containing anaconda
Here are the stack trace

[sylvain@sylvain-linux pyqt_ocr]$ kraken -i output.png converted.txt ocr
Loading RNN default     ✓
Traceback (most recent call last):
  File "/home/sylvain/anaconda3/bin/kraken", line 11, in <module> sys.exit(cli())
  File "/home/sylvain/anaconda3/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/sylvain/anaconda3/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/sylvain/anaconda3/lib/python3.6/site-packages/click/core.py", line 1093, in invoke
    return _process_result(rv)
  File "/home/sylvain/anaconda3/lib/python3.6/site-packages/click/core.py", line 1031, in _process_result
    **ctx.params)
  File "/home/sylvain/anaconda3/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/sylvain/anaconda3/lib/python3.6/site-packages/kraken/kraken.py", line 161, in process_pipeline
    task(base_image=base_image, input=input, output=output)
  File "/home/sylvain/anaconda3/lib/python3.6/site-packages/kraken/kraken.py", line 106, in recognizer
    bounds = json.load(fp)
  File "/home/sylvain/anaconda3/lib/python3.6/json/__init__.py", line 296, in load
    return loads(fp.read(),
  File "/home/sylvain/anaconda3/lib/python3.6/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x89 in position 0: invalid start byte

and same for windows
C:\Users\user11.HPO-SAMAT\PycharmProjects\Pyocr>kraken -i output.png converted.txt ocr
Loading RNN default     ✓
Traceback (most recent call last):
  File "c:\users\user11.hpo-samat\appdata\local\continuum\anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\user11.hpo-samat\appdata\local\continuum\anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\user11.HPO-SAMAT\AppData\Local\Continuum\Anaconda3\Scripts\kraken.exe\__main__.py", line 9, in <module>
  File "c:\users\user11.hpo-samat\appdata\local\continuum\anaconda3\lib\site-packages\click\core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "c:\users\user11.hpo-samat\appdata\local\continuum\anaconda3\lib\site-packages\click\core.py", line 697, in main
    rv = self.invoke(ctx)
  File "c:\users\user11.hpo-samat\appdata\local\continuum\anaconda3\lib\site-packages\click\core.py", line 1093, in invoke
    return _process_result(rv)
  File "c:\users\user11.hpo-samat\appdata\local\continuum\anaconda3\lib\site-packages\click\core.py", line 1031, in _process_result
    **ctx.params)
  File "c:\users\user11.hpo-samat\appdata\local\continuum\anaconda3\lib\site-packages\click\core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "c:\users\user11.hpo-samat\appdata\local\continuum\anaconda3\lib\site-packages\kraken\kraken.py", line 161, in process_pipeline
    task(base_image=base_image, input=input, output=output)
  File "c:\users\user11.hpo-samat\appdata\local\continuum\anaconda3\lib\site-packages\kraken\kraken.py", line 106, in recognizer
    bounds = json.load(fp)
  File "c:\users\user11.hpo-samat\appdata\local\continuum\anaconda3\lib\json\__init__.py", line 265, in load
    return loads(fp.read(),
  File "c:\users\user11.hpo-samat\appdata\local\continuum\anaconda3\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x8f in position 230: character maps to <undefined>

I'm not sure about my locale on windows but on linux(manjaro) it seems I'm using UTF8.
Hope it may helps ....

**Comment by mittagessen** [comment]
Sorry for taking so long to answer this but I hope you found the fix yourself, namely running the correct ``... binarize segment ocr`` sequence of commands. The OCR subcommand assumes it is running as part of a chain when no page segmentation is given explicitly, i.e. its input is the segmenter's output. Unfortunately it doesn't know if it is running in a chain or not and just took the image file and tried to parse it as a JSON segmentation file causing this indeed unhelpful error.

 I added some more enlightening error messages so people who aren't intimately familiar with the code are able to see the error of their ways.
