### ISSUE TITLE
UnboundLocalError: cannot access local variable 'nn' where it is not associated with a value

### ISSUE THREAD

**Issue by alitarek-dot** [mittagessen/kraken#660]
when running the command: kraken -i 2.jpg output.txt segment -bl ocr -m "C:\Users\ali\Downloads\catmus-print-fondue-large.mlmodel"
>>
Fail to import BlobReader from libmilstoragepython. No module named 'coremltools.libmilstoragepython'
Failed to load _MLModelProxy: No module named 'coremltools.libcoremlpython'
Fail to import BlobWriter from libmilstoragepython. No module named 'coremltools.libmilstoragepython'
Loading RNN C   ✓
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\ali\Desktop\Cloudilic\Projects\LLM-function-block\florence\scripts\kraken.exe\__main__.py", line 7, in <module>
  File "C:\Users\ali\Desktop\Cloudilic\Projects\LLM-function-block\florence\Lib\site-packages\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ali\Desktop\Cloudilic\Projects\LLM-function-block\florence\Lib\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "C:\Users\ali\Desktop\Cloudilic\Projects\LLM-function-block\florence\Lib\site-packages\click\core.py", line 1289, in invoke
    rv.append(sub_ctx.command.invoke(sub_ctx))
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ali\Desktop\Cloudilic\Projects\LLM-function-block\florence\Lib\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ali\Desktop\Cloudilic\Projects\LLM-function-block\florence\Lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ali\Desktop\Cloudilic\Projects\LLM-function-block\florence\Lib\site-packages\click\decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ali\Desktop\Cloudilic\Projects\LLM-function-block\florence\Lib\site-packages\kraken\kraken.py", line 364, in ocr
    print(nn)  # Add this line before nn[k].nn.set_num_threads(threads)
          ^^
UnboundLocalError: cannot access local variable 'nn' where it is not associated with a value

**Comment by alitarek-dot** [comment]
Please help
Also can you link me the Zenodo model for arabic language ? I am working on a use case for performing ocr on arabic numbers.

**Comment by jesusbft** [comment]
I'm not sure, but I believe Kraken running only in Linux, not Windows.

**Comment by alitarek-dot** [comment]
I see now, Thank you so much for responding :)
