### ISSUE TITLE
kraken get 10.5281/zenodo.10592716 -> gives me this error: KeyError: 'type' 

### ISSUE THREAD

**Issue by alitarek-dot** [mittagessen/kraken#661]
When running the command: kraken get 10.5281/zenodo.10592716
>> 
Retrieving model .Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\ali\Desktop\Cloudilic\Projects\LLM-function-block\florence\scripts\kraken.exe\__main__.py", line 7, in <module>
  File "C:\Users\ali\Desktop\Cloudilic\Projects\LLM-function-block\florence\Lib\site-packages\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ali\Desktop\Cloudilic\Projects\LLM-function-block\florence\Lib\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "C:\Users\ali\Desktop\Cloudilic\Projects\LLM-function-block\florence\Lib\site-packages\click\core.py", line 1289, in invoke
    rv.append(sub_ctx.command.invoke(sub_ctx))
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ali\Desktop\Cloudilic\Projects\LLM-function-block\florence\Lib\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ali\Desktop\Cloudilic\Projects\LLM-function-block\florence\Lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ali\Desktop\Cloudilic\Projects\LLM-function-block\florence\Lib\site-packages\click\decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ali\Desktop\Cloudilic\Projects\LLM-function-block\florence\Lib\site-packages\kraken\kraken.py", line 445, in get
    filename = repo.get_model(model_id, click.get_app_dir(APP_NAME),
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ali\Desktop\Cloudilic\Projects\LLM-function-block\florence\Lib\site-packages\kraken\repo.py", line 120, in get_model
    model_url = [x['links']['self'] for x in metadata['files'] if x['type'] == 'mlmodel'][0]
                                                                  ~^^^^^^^^
KeyError: 'type'

**Comment by jesusbft** [comment]
I'm not sure, but I believe Kraken running only in Linux, not Windows.

**Comment by alitarek-dot** [comment]
Thank you
