### ISSUE TITLE
kraken get 10.5281/zenodo.10592716 -> gives me this error which probably related to Zenodo API: KeyError: 'type'

### ISSUE THREAD

**Issue by alitarek-dot** [mittagessen/kraken#662]
When running this command:  kraken get 10.5281/zenodo.10592716
I get this error
>> 
Retrieving model .Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\ali\Desktop\Cloudilic\Projects\LLM-function-block\florence\scripts\kraken.exe\__main__.py", line 7, in <module>
  File "C:\Users\ali\Desktop\Cloudilic\Projects\LLM-function-block\florence\Lib\site-packages\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ali\Desktop\Cloudilic\Projects\LLM-function-block\florence\Lib\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "C:\Users\ali\Desktop\Cloudilic\Projects\LLM-function-block\florence\Lib\site-packages\click\core.py", line 1289, in invoke
    rv.append(sub_ctx.command.invoke(sub_ctx))
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ali\Desktop\Cloudilic\Projects\LLM-function-block\florence\Lib\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ali\Desktop\Cloudilic\Projects\LLM-function-block\florence\Lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ali\Desktop\Cloudilic\Projects\LLM-function-block\florence\Lib\site-packages\click\decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ali\Desktop\Cloudilic\Projects\LLM-function-block\florence\Lib\site-packages\kraken\kraken.py", line 445, in get
    filename = repo.get_model(model_id, click.get_app_dir(APP_NAME),
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ali\Desktop\Cloudilic\Projects\LLM-function-block\florence\Lib\site-packages\kraken\repo.py", line 120, in get_model
    model_url = [x['links']['self'] for x in metadata['files'] if x['type'] == 'mlmodel'][0]
                                                                  ~^^^^^^^^
KeyError: 'type'

**Comment by mittagessen** [comment]
You're not running the latest version of kraken. Zenodo changed the API
at some point so older releases will not be able to interact with the
repository.

**Comment by alitarek-dot** [comment]
when I try running pip install --upgrade kraken 
I get that requirement already satisfied kraken-2.0.8
kraken==2.0.8
is that the latest version ? @mittagessen

**Comment by alitarek-dot** [comment]
Can you please provide the official documentation link? Thank you

**Comment by mittagessen** [comment]
On 24/11/18 03:45AM, Ali Tarek Ali Abdulfattah Sakr wrote:
> when I try running pip install --upgrade kraken 
> I get that requirement already satisfied kraken-2.0.8
> kraken==2.0.8
> is that the latest version ? @mittagessen 

No, the latest version is 5.2.9. You're probably using an ancient
interpreter version of python that 2.0.8 supports but got deprecated in
anything newer.

The official docs can be found here [0].

[0] https://kraken.re

**Comment by alitarek-dot** [comment]
Thank you so much sir, I checked the docs and indeed 5.2.9 is the latest version, I don't know why my pip sees kraken v2.0.8 as the final version, that's so weird.
