### ISSUE TITLE
Kraken doesn't work with clstm models under macOS High Sierra (Getting error: Model file is not a pickle)

### ISSUE THREAD

**Issue by eqbal** [mittagessen/kraken#79]
I'm using MacBook Pro (15-inch, 2018) with macOS High Sierra v(10.13.6).
Using my python `Python 2.7.15` I installed Kraken (0.9.16) using `pip` as described in the README file.
I then installed the default model, then Installed `arabic-beirut-200` model using `kraken get` (note that I found this model using `kraken list`):

```
$ kraken get default
Retrieving model	✓
$ kraken get arabic-beirut-200
Retrieving model
```
First, I couldn't find the new installed model `arabic-beirut-200` (there is no `~/.kraken` folder) and it doesn't look I can use the new model:

```
$ kraken -i test_ara_ocr.tif out_kraken.txt binarize segment ocr -m arabic-beirut-200.clstm
Loading RNN default	[0.0081] Model file is not a pickle
✗
Traceback (most recent call last):
  File "/usr/local/bin/kraken", line 11, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 1092, in invoke
    rv.append(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/kraken/kraken.py", line 285, in ocr
    rnn = models.load_any(location)
  File "/usr/local/lib/python2.7/site-packages/kraken/lib/models.py", line 222, in load_any
    seq = load_pyrnn(fname)
  File "/usr/local/lib/python2.7/site-packages/kraken/lib/models.py", line 347, in load_pyrnn
    raise KrakenInvalidModelException(str(e))
kraken.lib.exceptions.KrakenInvalidModelException: invalid load key, '
```

Not sure what I'm doing wrong above? Any help would be highly appreciated.

**Comment by mittagessen** [comment]
kraken only works on Linux/*BSD systems. The error is shown because the clstm bindings aren't installed as there are no binary packages on pypi for them and I've got no system to build them on. I'd recommend using an ubuntu virtual machine or similar.
