### ISSUE TITLE
TypeError: unhashable type: 'list'

### ISSUE THREAD

**Issue by Usamamalik007** [mittagessen/kraken#95]
I am running script:
kraken -i 01000a.png a.txt binarize segment ocr -m model_best.mlmodel
I am getting error unhashable type list.
Traceback (most recent call last):
  File "/home/usama/anaconda2/envs/kraken/bin/kraken", line 11, in <module>
    sys.exit(cli())
  File "/home/usama/anaconda2/envs/kraken/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/usama/anaconda2/envs/kraken/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/usama/anaconda2/envs/kraken/lib/python3.7/site-packages/click/core.py", line 1164, in invoke
    return _process_result(rv)
  File "/home/usama/anaconda2/envs/kraken/lib/python3.7/site-packages/click/core.py", line 1102, in _process_result
    **ctx.params)
  File "/home/usama/anaconda2/envs/kraken/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/usama/anaconda2/envs/kraken/lib/python3.7/site-packages/kraken/kraken.py", line 220, in process_pipeline
    task(base_image=base_image, input=input, output=output)
  File "/home/usama/anaconda2/envs/kraken/lib/python3.7/site-packages/kraken/kraken.py", line 157, in recognizer
    for pred in bar:
  File "/home/usama/anaconda2/envs/kraken/lib/python3.7/site-packages/click/_termui_impl.py", line 285, in generator
    for rv in self.iter:
  File "/home/usama/anaconda2/envs/kraken/lib/python3.7/site-packages/kraken/rpred.py", line 182, in mm_rpred
    miss = [x[0] for x in bounds['boxes'] if not nets.get(x[0])]
  File "/home/usama/anaconda2/envs/kraken/lib/python3.7/site-packages/kraken/rpred.py", line 182, in <listcomp>
    miss = [x[0] for x in bounds['boxes'] if not nets.get(x[0])]
TypeError: unhashable type: 'list'

**Comment by MrOCR** [comment]
Error confirmed
